/* ==========================================================================
   Filmy, z których ścieżek dźwiękowych zbieramy utwory do kategorii „filmowa”.
   --------------------------------------------------------------------------
   Kategoria filmowa nie zbiera się po wykonawcach jak reszta: utwór musi mieć
   przypisany FILM, bo to on jest odpowiedzią w pytaniu. Więc tutaj trzymamy
   filmy, a sklep dokłada do każdego tytuły, wykonawców i podglądy.

   Rok przy filmie jest po to, żeby sprawdzić rok ze sklepu. Ścieżka dźwiękowa
   wychodzi razem z filmem, więc wydanie oddalone o kilka lat to prawie na pewno
   wznowienie albo zupełnie inny album, i takie odrzucamy. To mocniejsze
   zabezpieczenie niż przy wykonawcach, gdzie nie ma się do czego odwołać.

   Czego tu świadomie NIE ma: filmów, w których najbardziej znany utwór nazywa
   się tak samo jak film. Takie wpisy nadal działają (gra pokaże wtedy
   wykonawcę zamiast tytułu, patrz zdradzaFilm w js/katalog.js), ale dobre
   pytanie filmowe wychodzi przede wszystkim z piosenki, której tytuł nie jest
   nazwą filmu.
   ========================================================================== */

export const FILMY = [
  // --- lata 60. ---
  { nazwa: 'West Side Story', rok: 1961 },
  { nazwa: "Breakfast at Tiffany's", rok: 1961 },
  { nazwa: 'Lawrence of Arabia', rok: 1962 },
  { nazwa: 'Dr. No', rok: 1962 },
  { nazwa: 'My Fair Lady', rok: 1964 },
  { nazwa: 'Mary Poppins', rok: 1964 },
  { nazwa: "A Hard Day's Night", rok: 1964 },
  { nazwa: 'The Sound of Music', rok: 1965 },
  { nazwa: 'Doctor Zhivago', rok: 1965 },
  { nazwa: 'The Graduate', rok: 1967 },
  { nazwa: 'The Jungle Book', rok: 1967 },
  { nazwa: '2001: A Space Odyssey', rok: 1968 },
  { nazwa: 'Oliver!', rok: 1968 },
  { nazwa: 'Easy Rider', rok: 1969 },
  { nazwa: 'Butch Cassidy and the Sundance Kid', rok: 1969 },

  // --- lata 70. ---
  { nazwa: 'Love Story', rok: 1970 },
  { nazwa: 'A Clockwork Orange', rok: 1971 },
  { nazwa: 'Willy Wonka & the Chocolate Factory', rok: 1971 },
  { nazwa: 'The Godfather', rok: 1972 },
  { nazwa: 'The Sting', rok: 1973 },
  { nazwa: 'The Exorcist', rok: 1973 },
  { nazwa: 'The Rocky Horror Picture Show', rok: 1975 },
  { nazwa: 'Rocky', rok: 1976 },
  { nazwa: 'Taxi Driver', rok: 1976 },
  { nazwa: 'A Star Is Born', rok: 1976 },
  { nazwa: 'Star Wars', rok: 1977 },
  { nazwa: 'Saturday Night Fever', rok: 1977 },
  { nazwa: 'Grease', rok: 1978 },
  { nazwa: 'Superman', rok: 1978 },
  { nazwa: 'Apocalypse Now', rok: 1979 },
  { nazwa: 'Alien', rok: 1979 },

  // --- lata 80. ---
  { nazwa: 'The Empire Strikes Back', rok: 1980 },
  { nazwa: 'Fame', rok: 1980 },
  { nazwa: 'The Blues Brothers', rok: 1980 },
  { nazwa: 'Raiders of the Lost Ark', rok: 1981 },
  { nazwa: 'Chariots of Fire', rok: 1981 },
  { nazwa: 'For Your Eyes Only', rok: 1981 },
  { nazwa: 'E.T. the Extra-Terrestrial', rok: 1982 },
  { nazwa: 'Blade Runner', rok: 1982 },
  { nazwa: 'Flashdance', rok: 1983 },
  { nazwa: 'Return of the Jedi', rok: 1983 },
  { nazwa: 'Footloose', rok: 1984 },
  { nazwa: 'Ghostbusters', rok: 1984 },
  { nazwa: 'The Terminator', rok: 1984 },
  { nazwa: 'Beverly Hills Cop', rok: 1984 },
  { nazwa: 'Purple Rain', rok: 1984 },
  { nazwa: 'Back to the Future', rok: 1985 },
  { nazwa: 'The Breakfast Club', rok: 1985 },
  { nazwa: 'Rocky IV', rok: 1985 },
  { nazwa: 'Top Gun', rok: 1986 },
  { nazwa: 'Pretty in Pink', rok: 1986 },
  { nazwa: 'Stand by Me', rok: 1986 },
  { nazwa: 'Dirty Dancing', rok: 1987 },
  { nazwa: 'The Lost Boys', rok: 1987 },
  { nazwa: 'La Bamba', rok: 1987 },
  { nazwa: 'Beetlejuice', rok: 1988 },
  { nazwa: 'Cocktail', rok: 1988 },
  { nazwa: 'Who Framed Roger Rabbit', rok: 1988 },
  { nazwa: 'Rain Man', rok: 1988 },
  { nazwa: 'Batman', rok: 1989 },
  { nazwa: 'The Little Mermaid', rok: 1989 },
  { nazwa: 'Dead Poets Society', rok: 1989 },
  { nazwa: 'When Harry Met Sally', rok: 1989 },

  // --- lata 90. ---
  { nazwa: 'Pretty Woman', rok: 1990 },
  { nazwa: 'Ghost', rok: 1990 },
  { nazwa: 'Edward Scissorhands', rok: 1990 },
  { nazwa: 'Home Alone', rok: 1990 },
  { nazwa: 'Dances with Wolves', rok: 1990 },
  { nazwa: 'Beauty and the Beast', rok: 1991 },
  { nazwa: 'Terminator 2: Judgment Day', rok: 1991 },
  { nazwa: 'Robin Hood: Prince of Thieves', rok: 1991 },
  { nazwa: 'The Silence of the Lambs', rok: 1991 },
  { nazwa: 'Aladdin', rok: 1992 },
  { nazwa: 'The Bodyguard', rok: 1992 },
  { nazwa: "Wayne's World", rok: 1992 },
  { nazwa: 'Jurassic Park', rok: 1993 },
  { nazwa: "Schindler's List", rok: 1993 },
  { nazwa: 'Sleepless in Seattle', rok: 1993 },
  { nazwa: 'The Nightmare Before Christmas', rok: 1993 },
  { nazwa: 'Philadelphia', rok: 1993 },
  { nazwa: 'The Lion King', rok: 1994 },
  { nazwa: 'Forrest Gump', rok: 1994 },
  { nazwa: 'Pulp Fiction', rok: 1994 },
  { nazwa: 'Speed', rok: 1994 },
  { nazwa: 'Braveheart', rok: 1995 },
  { nazwa: 'Toy Story', rok: 1995 },
  { nazwa: 'Pocahontas', rok: 1995 },
  { nazwa: 'Batman Forever', rok: 1995 },
  { nazwa: 'Waiting to Exhale', rok: 1995 },
  { nazwa: 'Trainspotting', rok: 1996 },
  { nazwa: 'Romeo + Juliet', rok: 1996 },
  { nazwa: 'Space Jam', rok: 1996 },
  { nazwa: 'The Hunchback of Notre Dame', rok: 1996 },
  { nazwa: 'Titanic', rok: 1997 },
  { nazwa: 'Men in Black', rok: 1997 },
  { nazwa: 'The Fifth Element', rok: 1997 },
  { nazwa: 'Good Will Hunting', rok: 1997 },
  { nazwa: 'Hercules', rok: 1997 },
  { nazwa: 'Armageddon', rok: 1998 },
  { nazwa: 'Mulan', rok: 1998 },
  { nazwa: 'The Big Lebowski', rok: 1998 },
  { nazwa: 'City of Angels', rok: 1998 },
  { nazwa: 'The Prince of Egypt', rok: 1998 },
  { nazwa: 'The Matrix', rok: 1999 },
  { nazwa: 'Tarzan', rok: 1999 },
  { nazwa: 'Notting Hill', rok: 1999 },
  { nazwa: 'American Beauty', rok: 1999 },
  { nazwa: 'Fight Club', rok: 1999 },

  // --- lata 2000. ---
  { nazwa: 'Gladiator', rok: 2000 },
  { nazwa: 'Almost Famous', rok: 2000 },
  { nazwa: 'O Brother, Where Art Thou?', rok: 2000 },
  { nazwa: 'Coyote Ugly', rok: 2000 },
  { nazwa: 'Moulin Rouge!', rok: 2001 },
  { nazwa: 'Shrek', rok: 2001 },
  { nazwa: "Harry Potter and the Sorcerer's Stone", rok: 2001 },
  { nazwa: 'The Lord of the Rings: The Fellowship of the Ring', rok: 2001 },
  { nazwa: 'Amélie', rok: 2001 },
  { nazwa: '8 Mile', rok: 2002 },
  { nazwa: 'Chicago', rok: 2002 },
  { nazwa: 'Spider-Man', rok: 2002 },
  { nazwa: 'Pirates of the Caribbean: The Curse of the Black Pearl', rok: 2003 },
  { nazwa: 'Love Actually', rok: 2003 },
  { nazwa: 'Kill Bill: Vol. 1', rok: 2003 },
  { nazwa: 'The Lord of the Rings: The Return of the King', rok: 2003 },
  { nazwa: 'Shrek 2', rok: 2004 },
  { nazwa: 'Garden State', rok: 2004 },
  { nazwa: 'Ray', rok: 2004 },
  { nazwa: 'The Incredibles', rok: 2004 },
  { nazwa: 'Batman Begins', rok: 2005 },
  { nazwa: 'Brokeback Mountain', rok: 2005 },
  { nazwa: 'Walk the Line', rok: 2005 },
  { nazwa: 'Pride & Prejudice', rok: 2005 },
  { nazwa: 'The Devil Wears Prada', rok: 2006 },
  { nazwa: 'Cars', rok: 2006 },
  { nazwa: 'Casino Royale', rok: 2006 },
  { nazwa: 'Dreamgirls', rok: 2006 },
  { nazwa: 'Once', rok: 2007 },
  { nazwa: 'Juno', rok: 2007 },
  { nazwa: 'Enchanted', rok: 2007 },
  { nazwa: 'Hairspray', rok: 2007 },
  { nazwa: 'Into the Wild', rok: 2007 },
  { nazwa: 'The Dark Knight', rok: 2008 },
  { nazwa: 'Mamma Mia!', rok: 2008 },
  { nazwa: 'Slumdog Millionaire', rok: 2008 },
  { nazwa: 'WALL-E', rok: 2008 },
  { nazwa: 'Twilight', rok: 2008 },
  { nazwa: 'Up', rok: 2009 },
  { nazwa: 'Avatar', rok: 2009 },
  { nazwa: 'The Hangover', rok: 2009 },

  // --- lata 2010. ---
  { nazwa: 'Inception', rok: 2010 },
  { nazwa: 'Tangled', rok: 2010 },
  { nazwa: 'Tron: Legacy', rok: 2010 },
  { nazwa: 'The Social Network', rok: 2010 },
  { nazwa: 'Black Swan', rok: 2010 },
  { nazwa: 'Drive', rok: 2011 },
  { nazwa: 'The Muppets', rok: 2011 },
  { nazwa: 'The Hunger Games', rok: 2012 },
  { nazwa: 'Les Misérables', rok: 2012 },
  { nazwa: 'Django Unchained', rok: 2012 },
  { nazwa: 'Pitch Perfect', rok: 2012 },
  { nazwa: 'Frozen', rok: 2013 },
  { nazwa: 'The Great Gatsby', rok: 2013 },
  { nazwa: 'Her', rok: 2013 },
  { nazwa: 'Guardians of the Galaxy', rok: 2014 },
  { nazwa: 'The Fault in Our Stars', rok: 2014 },
  { nazwa: 'Birdman', rok: 2014 },
  { nazwa: 'Whiplash', rok: 2014 },
  { nazwa: 'Fifty Shades of Grey', rok: 2015 },
  { nazwa: 'Straight Outta Compton', rok: 2015 },
  { nazwa: 'Inside Out', rok: 2015 },
  { nazwa: 'Suicide Squad', rok: 2016 },
  { nazwa: 'La La Land', rok: 2016 },
  { nazwa: 'Moana', rok: 2016 },
  { nazwa: 'Sing', rok: 2016 },
  { nazwa: 'Trolls', rok: 2016 },
  { nazwa: 'Rogue One: A Star Wars Story', rok: 2016 },
  { nazwa: 'Baby Driver', rok: 2017 },
  { nazwa: 'The Greatest Showman', rok: 2017 },
  { nazwa: 'Coco', rok: 2017 },
  { nazwa: 'Call Me by Your Name', rok: 2017 },
  { nazwa: 'Black Panther', rok: 2018 },
  { nazwa: 'A Star Is Born', rok: 2018 },
  { nazwa: 'Bohemian Rhapsody', rok: 2018 },
  { nazwa: 'Mary Poppins Returns', rok: 2018 },
  { nazwa: 'Spider-Man: Into the Spider-Verse', rok: 2018 },
  { nazwa: 'Rocketman', rok: 2019 },
  { nazwa: 'Frozen II', rok: 2019 },
  { nazwa: 'Joker', rok: 2019 },
  { nazwa: 'Toy Story 4', rok: 2019 },

  // --- lata 2020. ---
  { nazwa: 'Soul', rok: 2020 },
  { nazwa: 'Birds of Prey', rok: 2020 },
  { nazwa: 'Hamilton', rok: 2020 },
  { nazwa: 'Encanto', rok: 2021 },
  { nazwa: 'Dune', rok: 2021 },
  { nazwa: 'In the Heights', rok: 2021 },
  { nazwa: 'Spider-Man: No Way Home', rok: 2021 },
  { nazwa: 'Top Gun: Maverick', rok: 2022 },
  { nazwa: 'Elvis', rok: 2022 },
  { nazwa: 'The Batman', rok: 2022 },
  { nazwa: 'Everything Everywhere All at Once', rok: 2022 },
  { nazwa: 'Barbie', rok: 2023 },
  { nazwa: 'Oppenheimer', rok: 2023 },
  { nazwa: 'The Super Mario Bros. Movie', rok: 2023 },
  { nazwa: 'Wonka', rok: 2023 },
  { nazwa: 'Guardians of the Galaxy Vol. 3', rok: 2023 },
  { nazwa: 'Wish', rok: 2023 },
  { nazwa: 'Dune: Part Two', rok: 2024 },
  { nazwa: 'Wicked', rok: 2024 },
  { nazwa: 'Inside Out 2', rok: 2024 },
  { nazwa: 'Moana 2', rok: 2024 },
  { nazwa: 'Deadpool & Wolverine', rok: 2024 },
  { nazwa: 'KPop Demon Hunters', rok: 2025 },
];
