/* ==========================================================================
   Jaka to Melodia — katalog utworów
   --------------------------------------------------------------------------
   Jeden wpis = jedna piosenka. Adresy 30-sekundowych podglądów nie stoją tutaj;
   dokłada je narzedzia/pobierz-podglady.mjs, dopasowując wpis do iTunes po
   tytule i wykonawcy (wynik ląduje w dane/podglady.json).

   Pola:
     tytul      — dokładnie tak, jak w sklepie muzycznym (bez „(Remastered)” itp.)
     wykonawca  — główny wykonawca; featuringi jako „A feat. B”
     rok        — rok wydania singla; z niego bierze się dekada 80/90/00/10/20
     gatunek    — kategoria wybierana w grze:
                  'pop' | 'rock' | 'rap' | 'dance' | 'rnb' | 'polskie'
     styl       — tylko przy polskich: pod jaki gatunek podpada. Gra nie pokazuje
                  tego nigdzie, używa wyłącznie do dobierania błędnych odpowiedzi,
                  żeby do polskiego rocka nie podstawiała disco polo.

   Dopisanie piosenki to jedna linijka w odpowiedniej sekcji. Potem:
     node narzedzia/sprawdz-dane.mjs      — kontrola (duble, literówki, braki)
   a workflow „Jaka to Melodia” sam dociągnie podgląd przy najbliższym pushu.
   Utwór bez znalezionego podglądu po prostu nie wejdzie do losowania.
   ========================================================================== */

export const UTWORY = [

  // ======================= LATA 1980. =======================
  // --- pop (22) ---
  { tytul: 'In the Air Tonight', wykonawca: 'Phil Collins', rok: 1981, gatunek: 'pop' },
  { tytul: 'Rio', wykonawca: 'Duran Duran', rok: 1982, gatunek: 'pop' },
  { tytul: 'Africa', wykonawca: 'Toto', rok: 1982, gatunek: 'pop' },
  { tytul: 'Total Eclipse of the Heart', wykonawca: 'Bonnie Tyler', rok: 1983, gatunek: 'pop' },
  { tytul: 'Girls Just Want to Have Fun', wykonawca: 'Cyndi Lauper', rok: 1983, gatunek: 'pop' },
  { tytul: 'Sweet Dreams (Are Made of This)', wykonawca: 'Eurythmics', rok: 1983, gatunek: 'pop' },
  { tytul: 'Billie Jean', wykonawca: 'Michael Jackson', rok: 1983, gatunek: 'pop' },
  { tytul: 'Beat It', wykonawca: 'Michael Jackson', rok: 1983, gatunek: 'pop' },
  { tytul: 'Careless Whisper', wykonawca: 'George Michael', rok: 1984, gatunek: 'pop' },
  { tytul: 'Wake Me Up Before You Go-Go', wykonawca: 'Wham!', rok: 1984, gatunek: 'pop' },
  { tytul: 'Take On Me', wykonawca: 'a-ha', rok: 1985, gatunek: 'pop' },
  { tytul: 'Running Up That Hill', wykonawca: 'Kate Bush', rok: 1985, gatunek: 'pop' },
  { tytul: 'Material Girl', wykonawca: 'Madonna', rok: 1985, gatunek: 'pop' },
  { tytul: "You're My Heart, You're My Soul", wykonawca: 'Modern Talking', rok: 1985, gatunek: 'pop' },
  { tytul: "Don't You (Forget About Me)", wykonawca: 'Simple Minds', rok: 1985, gatunek: 'pop' },
  { tytul: 'Everybody Wants to Rule the World', wykonawca: 'Tears for Fears', rok: 1985, gatunek: 'pop' },
  { tytul: 'Venus', wykonawca: 'Bananarama', rok: 1986, gatunek: 'pop' },
  { tytul: 'The Final Countdown', wykonawca: 'Europe', rok: 1986, gatunek: 'pop' },
  { tytul: 'Never Gonna Give You Up', wykonawca: 'Rick Astley', rok: 1987, gatunek: 'pop' },
  { tytul: 'I Wanna Dance with Somebody', wykonawca: 'Whitney Houston', rok: 1987, gatunek: 'pop' },
  { tytul: 'Personal Jesus', wykonawca: 'Depeche Mode', rok: 1989, gatunek: 'pop' },
  { tytul: 'Like a Prayer', wykonawca: 'Madonna', rok: 1989, gatunek: 'pop' },
  // --- rock (21) ---
  { tytul: 'Back in Black', wykonawca: 'AC/DC', rok: 1980, gatunek: 'rock' },
  { tytul: 'Love Will Tear Us Apart', wykonawca: 'Joy Division', rok: 1980, gatunek: 'rock' },
  { tytul: 'Another One Bites the Dust', wykonawca: 'Queen', rok: 1980, gatunek: 'rock' },
  { tytul: "Don't Stop Believin'", wykonawca: 'Journey', rok: 1981, gatunek: 'rock' },
  { tytul: 'Eye of the Tiger', wykonawca: 'Survivor', rok: 1982, gatunek: 'rock' },
  { tytul: 'The Trooper', wykonawca: 'Iron Maiden', rok: 1983, gatunek: 'rock' },
  { tytul: 'Every Breath You Take', wykonawca: 'The Police', rok: 1983, gatunek: 'rock' },
  { tytul: 'Purple Rain', wykonawca: 'Prince', rok: 1984, gatunek: 'rock' },
  { tytul: 'Radio Ga Ga', wykonawca: 'Queen', rok: 1984, gatunek: 'rock' },
  { tytul: "We're Not Gonna Take It", wykonawca: 'Twisted Sister', rok: 1984, gatunek: 'rock' },
  { tytul: 'Jump', wykonawca: 'Van Halen', rok: 1984, gatunek: 'rock' },
  { tytul: 'Money for Nothing', wykonawca: 'Dire Straits', rok: 1985, gatunek: 'rock' },
  { tytul: "Livin' on a Prayer", wykonawca: 'Bon Jovi', rok: 1986, gatunek: 'rock' },
  { tytul: 'You Give Love a Bad Name', wykonawca: 'Bon Jovi', rok: 1986, gatunek: 'rock' },
  { tytul: 'Master of Puppets', wykonawca: 'Metallica', rok: 1986, gatunek: 'rock' },
  { tytul: 'Pour Some Sugar on Me', wykonawca: 'Def Leppard', rok: 1987, gatunek: 'rock' },
  { tytul: "Sweet Child o' Mine", wykonawca: "Guns N' Roses", rok: 1987, gatunek: 'rock' },
  { tytul: 'Welcome to the Jungle', wykonawca: "Guns N' Roses", rok: 1987, gatunek: 'rock' },
  { tytul: 'Just Like Heaven', wykonawca: 'The Cure', rok: 1987, gatunek: 'rock' },
  { tytul: 'With or Without You', wykonawca: 'U2', rok: 1987, gatunek: 'rock' },
  { tytul: 'Every Rose Has Its Thorn', wykonawca: 'Poison', rok: 1988, gatunek: 'rock' },
  // --- rap / hip-hop (10) ---
  { tytul: 'The Message', wykonawca: 'Grandmaster Flash & The Furious Five', rok: 1982, gatunek: 'rap' },
  { tytul: '(You Gotta) Fight for Your Right (To Party!)', wykonawca: 'Beastie Boys', rok: 1986, gatunek: 'rap' },
  { tytul: 'Walk This Way', wykonawca: 'Run-DMC', rok: 1986, gatunek: 'rap' },
  { tytul: 'Paid in Full', wykonawca: 'Eric B. & Rakim', rok: 1987, gatunek: 'rap' },
  { tytul: 'I Need Love', wykonawca: 'LL Cool J', rok: 1987, gatunek: 'rap' },
  { tytul: 'Push It', wykonawca: 'Salt-N-Pepa', rok: 1987, gatunek: 'rap' },
  { tytul: 'Straight Outta Compton', wykonawca: 'N.W.A', rok: 1988, gatunek: 'rap' },
  { tytul: 'It Takes Two', wykonawca: 'Rob Base & DJ E-Z Rock', rok: 1988, gatunek: 'rap' },
  { tytul: 'Wild Thing', wykonawca: 'Tone Lōc', rok: 1988, gatunek: 'rap' },
  { tytul: 'Fight the Power', wykonawca: 'Public Enemy', rok: 1989, gatunek: 'rap' },
  // --- dance / elektronika (16) ---
  { tytul: 'Tainted Love', wykonawca: 'Soft Cell', rok: 1981, gatunek: 'dance' },
  { tytul: 'Blue Monday', wykonawca: 'New Order', rok: 1983, gatunek: 'dance' },
  { tytul: 'Vamos a la playa', wykonawca: 'Righeira', rok: 1983, gatunek: 'dance' },
  { tytul: 'Dolce Vita', wykonawca: 'Ryan Paris', rok: 1983, gatunek: 'dance' },
  { tytul: "You're a Woman", wykonawca: 'Bad Boys Blue', rok: 1985, gatunek: 'dance' },
  { tytul: 'Tarzan Boy', wykonawca: 'Baltimora', rok: 1985, gatunek: 'dance' },
  { tytul: 'You Spin Me Round (Like a Record)', wykonawca: 'Dead or Alive', rok: 1985, gatunek: 'dance' },
  { tytul: 'Rock Me Amadeus', wykonawca: 'Falco', rok: 1985, gatunek: 'dance' },
  { tytul: 'Live Is Life', wykonawca: 'Opus', rok: 1985, gatunek: 'dance' },
  { tytul: 'West End Girls', wykonawca: 'Pet Shop Boys', rok: 1985, gatunek: 'dance' },
  { tytul: "'Cause You Are Young", wykonawca: 'C.C. Catch', rok: 1986, gatunek: 'dance' },
  { tytul: 'Brother Louie', wykonawca: 'Modern Talking', rok: 1986, gatunek: 'dance' },
  { tytul: 'Touch Me (I Want Your Body)', wykonawca: 'Samantha Fox', rok: 1986, gatunek: 'dance' },
  { tytul: 'Boys (Summertime Love)', wykonawca: 'Sabrina', rok: 1987, gatunek: 'dance' },
  { tytul: 'Ride on Time', wykonawca: 'Black Box', rok: 1989, gatunek: 'dance' },
  { tytul: 'Pump Up the Jam', wykonawca: 'Technotronic', rok: 1989, gatunek: 'dance' },
  // --- r&b / soul (10) ---
  { tytul: 'Celebration', wykonawca: 'Kool & The Gang', rok: 1980, gatunek: 'rnb' },
  { tytul: "Let's Groove", wykonawca: 'Earth, Wind & Fire', rok: 1981, gatunek: 'rnb' },
  { tytul: 'Sexual Healing', wykonawca: 'Marvin Gaye', rok: 1982, gatunek: 'rnb' },
  { tytul: 'I Feel for You', wykonawca: 'Chaka Khan', rok: 1984, gatunek: 'rnb' },
  { tytul: 'Hello', wykonawca: 'Lionel Richie', rok: 1984, gatunek: 'rnb' },
  { tytul: "What's Love Got to Do with It", wykonawca: 'Tina Turner', rok: 1984, gatunek: 'rnb' },
  { tytul: 'Kiss', wykonawca: 'Prince', rok: 1986, gatunek: 'rnb' },
  { tytul: 'Greatest Love of All', wykonawca: 'Whitney Houston', rok: 1986, gatunek: 'rnb' },
  { tytul: 'Smooth Criminal', wykonawca: 'Michael Jackson', rok: 1987, gatunek: 'rnb' },
  { tytul: 'My Prerogative', wykonawca: 'Bobby Brown', rok: 1988, gatunek: 'rnb' },
  // --- polskie (15) ---
  { tytul: 'Kocham cię, kochanie moje', wykonawca: 'Maanam', rok: 1980, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Wszystko czego dziś chcę', wykonawca: 'Izabela Trojanowska', rok: 1981, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Autobiografia', wykonawca: 'Perfect', rok: 1981, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Chcemy być sobą', wykonawca: 'Perfect', rok: 1981, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Biała flaga', wykonawca: 'Republika', rok: 1981, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Jolka, Jolka pamiętasz', wykonawca: 'Budka Suflera', rok: 1982, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Słodkiego miłego życia', wykonawca: 'Kombi', rok: 1983, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Mniej niż zero', wykonawca: 'Lady Pank', rok: 1983, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Przeżyj to sam', wykonawca: 'Lombard', rok: 1983, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Andzia i ja', wykonawca: 'Oddział Zamknięty', rok: 1983, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Józek, nie daruję ci tej nocy', wykonawca: 'Bajm', rok: 1984, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Zaopiekuj się mną', wykonawca: 'Rezerwat', rok: 1985, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Zawsze tam gdzie ty', wykonawca: 'Lady Pank', rok: 1986, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Nasz Disneyland', wykonawca: 'Papa Dance', rok: 1986, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Arahja', wykonawca: 'Kult', rok: 1988, gatunek: 'polskie', styl: 'rock' },

  // ======================= LATA 1990. =======================
  // --- pop (13) ---
  { tytul: 'Joyride', wykonawca: 'Roxette', rok: 1991, gatunek: 'pop' },
  { tytul: 'Ironic', wykonawca: 'Alanis Morissette', rok: 1995, gatunek: 'pop' },
  { tytul: 'Wannabe', wykonawca: 'Spice Girls', rok: 1996, gatunek: 'pop' },
  { tytul: 'My Heart Will Go On', wykonawca: 'Céline Dion', rok: 1997, gatunek: 'pop' },
  { tytul: 'Tubthumping', wykonawca: 'Chumbawamba', rok: 1997, gatunek: 'pop' },
  { tytul: 'MMMBop', wykonawca: 'Hanson', rok: 1997, gatunek: 'pop' },
  { tytul: 'Torn', wykonawca: 'Natalie Imbruglia', rok: 1997, gatunek: 'pop' },
  { tytul: 'Angels', wykonawca: 'Robbie Williams', rok: 1997, gatunek: 'pop' },
  { tytul: 'Truly Madly Deeply', wykonawca: 'Savage Garden', rok: 1997, gatunek: 'pop' },
  { tytul: '...Baby One More Time', wykonawca: 'Britney Spears', rok: 1998, gatunek: 'pop' },
  { tytul: "That Don't Impress Me Much", wykonawca: 'Shania Twain', rok: 1998, gatunek: 'pop' },
  { tytul: 'I Want It That Way', wykonawca: 'Backstreet Boys', rok: 1999, gatunek: 'pop' },
  { tytul: "Livin' la Vida Loca", wykonawca: 'Ricky Martin', rok: 1999, gatunek: 'pop' },
  // --- rock (21) ---
  { tytul: 'Thunderstruck', wykonawca: 'AC/DC', rok: 1990, gatunek: 'rock' },
  { tytul: 'Wind of Change', wykonawca: 'Scorpions', rok: 1990, gatunek: 'rock' },
  { tytul: '(Everything I Do) I Do It for You', wykonawca: 'Bryan Adams', rok: 1991, gatunek: 'rock' },
  { tytul: 'November Rain', wykonawca: "Guns N' Roses", rok: 1991, gatunek: 'rock' },
  { tytul: 'Nothing Else Matters', wykonawca: 'Metallica', rok: 1991, gatunek: 'rock' },
  { tytul: 'Enter Sandman', wykonawca: 'Metallica', rok: 1991, gatunek: 'rock' },
  { tytul: 'Smells Like Teen Spirit', wykonawca: 'Nirvana', rok: 1991, gatunek: 'rock' },
  { tytul: 'Come as You Are', wykonawca: 'Nirvana', rok: 1991, gatunek: 'rock' },
  { tytul: 'Alive', wykonawca: 'Pearl Jam', rok: 1991, gatunek: 'rock' },
  { tytul: 'Under the Bridge', wykonawca: 'Red Hot Chili Peppers', rok: 1991, gatunek: 'rock' },
  { tytul: 'Creep', wykonawca: 'Radiohead', rok: 1992, gatunek: 'rock' },
  { tytul: 'Killing in the Name', wykonawca: 'Rage Against the Machine', rok: 1992, gatunek: 'rock' },
  { tytul: "What's Up?", wykonawca: '4 Non Blondes', rok: 1993, gatunek: 'rock' },
  { tytul: 'Basket Case', wykonawca: 'Green Day', rok: 1994, gatunek: 'rock' },
  { tytul: 'Black Hole Sun', wykonawca: 'Soundgarden', rok: 1994, gatunek: 'rock' },
  { tytul: 'Zombie', wykonawca: 'The Cranberries', rok: 1994, gatunek: 'rock' },
  { tytul: 'Wonderwall', wykonawca: 'Oasis', rok: 1995, gatunek: 'rock' },
  { tytul: "Don't Speak", wykonawca: 'No Doubt', rok: 1996, gatunek: 'rock' },
  { tytul: 'Song 2', wykonawca: 'Blur', rok: 1997, gatunek: 'rock' },
  { tytul: 'Pretty Fly (For a White Guy)', wykonawca: 'The Offspring', rok: 1998, gatunek: 'rock' },
  { tytul: 'Californication', wykonawca: 'Red Hot Chili Peppers', rok: 1999, gatunek: 'rock' },
  // --- rap / hip-hop (15) ---
  { tytul: "Nuthin' but a \"G\" Thang", wykonawca: 'Dr. Dre', rok: 1992, gatunek: 'rap' },
  { tytul: 'Jump Around', wykonawca: 'House of Pain', rok: 1992, gatunek: 'rap' },
  { tytul: 'Insane in the Brain', wykonawca: 'Cypress Hill', rok: 1993, gatunek: 'rap' },
  { tytul: 'Hip Hop Hooray', wykonawca: 'Naughty by Nature', rok: 1993, gatunek: 'rap' },
  { tytul: 'C.R.E.A.M.', wykonawca: 'Wu-Tang Clan', rok: 1993, gatunek: 'rap' },
  { tytul: 'Sabotage', wykonawca: 'Beastie Boys', rok: 1994, gatunek: 'rap' },
  { tytul: 'Gin and Juice', wykonawca: 'Snoop Dogg', rok: 1994, gatunek: 'rap' },
  { tytul: 'Juicy', wykonawca: 'The Notorious B.I.G.', rok: 1994, gatunek: 'rap' },
  { tytul: 'Regulate', wykonawca: 'Warren G', rok: 1994, gatunek: 'rap' },
  { tytul: 'California Love', wykonawca: '2Pac', rok: 1995, gatunek: 'rap' },
  { tytul: "Gangsta's Paradise", wykonawca: 'Coolio', rok: 1995, gatunek: 'rap' },
  { tytul: "I'll Be Missing You", wykonawca: 'Puff Daddy', rok: 1997, gatunek: 'rap' },
  { tytul: 'Changes', wykonawca: '2Pac', rok: 1998, gatunek: 'rap' },
  { tytul: 'Doo Wop (That Thing)', wykonawca: 'Lauryn Hill', rok: 1998, gatunek: 'rap' },
  { tytul: 'My Name Is', wykonawca: 'Eminem', rok: 1999, gatunek: 'rap' },
  // --- dance / elektronika (25) ---
  { tytul: "It's My Life", wykonawca: 'Dr. Alban', rok: 1992, gatunek: 'dance' },
  { tytul: 'Rhythm Is a Dancer', wykonawca: 'Snap!', rok: 1992, gatunek: 'dance' },
  { tytul: 'No Limit', wykonawca: '2 Unlimited', rok: 1993, gatunek: 'dance' },
  { tytul: 'The Sign', wykonawca: 'Ace of Base', rok: 1993, gatunek: 'dance' },
  { tytul: 'The Rhythm of the Night', wykonawca: 'Corona', rok: 1993, gatunek: 'dance' },
  { tytul: 'Mr. Vain', wykonawca: 'Culture Beat', rok: 1993, gatunek: 'dance' },
  { tytul: 'What Is Love', wykonawca: 'Haddaway', rok: 1993, gatunek: 'dance' },
  { tytul: 'Scatman (Ski-Ba-Bop-Ba-Dop-Bop)', wykonawca: 'Scatman John', rok: 1994, gatunek: 'dance' },
  { tytul: 'Saturday Night', wykonawca: 'Whigfield', rok: 1994, gatunek: 'dance' },
  { tytul: 'Be My Lover', wykonawca: 'La Bouche', rok: 1995, gatunek: 'dance' },
  { tytul: 'Macarena', wykonawca: 'Los del Río', rok: 1995, gatunek: 'dance' },
  { tytul: 'Children', wykonawca: 'Robert Miles', rok: 1995, gatunek: 'dance' },
  { tytul: 'Freed from Desire', wykonawca: 'Gala', rok: 1996, gatunek: 'dance' },
  { tytul: 'Coco Jamboo', wykonawca: 'Mr. President', rok: 1996, gatunek: 'dance' },
  { tytul: 'Encore une fois', wykonawca: 'Sash!', rok: 1996, gatunek: 'dance' },
  { tytul: 'Firestarter', wykonawca: 'The Prodigy', rok: 1996, gatunek: 'dance' },
  { tytul: 'Barbie Girl', wykonawca: 'Aqua', rok: 1997, gatunek: 'dance' },
  { tytul: 'Around the World', wykonawca: 'Daft Punk', rok: 1997, gatunek: 'dance' },
  { tytul: '9 PM (Till I Come)', wykonawca: 'ATB', rok: 1998, gatunek: 'dance' },
  { tytul: 'Believe', wykonawca: 'Cher', rok: 1998, gatunek: 'dance' },
  { tytul: 'Praise You', wykonawca: 'Fatboy Slim', rok: 1998, gatunek: 'dance' },
  { tytul: 'Boom, Boom, Boom, Boom!!', wykonawca: 'Vengaboys', rok: 1998, gatunek: 'dance' },
  { tytul: 'Better Off Alone', wykonawca: 'Alice Deejay', rok: 1999, gatunek: 'dance' },
  { tytul: 'Sandstorm', wykonawca: 'Darude', rok: 1999, gatunek: 'dance' },
  { tytul: 'Blue (Da Ba Dee)', wykonawca: 'Eiffel 65', rok: 1999, gatunek: 'dance' },
  // --- r&b / soul (12) ---
  { tytul: 'End of the Road', wykonawca: 'Boyz II Men', rok: 1992, gatunek: 'rnb' },
  { tytul: 'I Will Always Love You', wykonawca: 'Whitney Houston', rok: 1992, gatunek: 'rnb' },
  { tytul: 'Kiss from a Rose', wykonawca: 'Seal', rok: 1994, gatunek: 'rnb' },
  { tytul: 'Waterfalls', wykonawca: 'TLC', rok: 1994, gatunek: 'rnb' },
  { tytul: 'Fantasy', wykonawca: 'Mariah Carey', rok: 1995, gatunek: 'rnb' },
  { tytul: 'This Is How We Do It', wykonawca: 'Montell Jordan', rok: 1995, gatunek: 'rnb' },
  { tytul: 'No Diggity', wykonawca: 'Blackstreet', rok: 1996, gatunek: 'rnb' },
  { tytul: 'Return of the Mack', wykonawca: 'Mark Morrison', rok: 1996, gatunek: 'rnb' },
  { tytul: 'Un-Break My Heart', wykonawca: 'Toni Braxton', rok: 1996, gatunek: 'rnb' },
  { tytul: 'The Boy Is Mine', wykonawca: 'Brandy & Monica', rok: 1998, gatunek: 'rnb' },
  { tytul: 'Say My Name', wykonawca: "Destiny's Child", rok: 1999, gatunek: 'rnb' },
  { tytul: 'No Scrubs', wykonawca: 'TLC', rok: 1999, gatunek: 'rnb' },
  // --- polskie (21) ---
  { tytul: 'Kocham cię jak Irlandię', wykonawca: 'Kobranocka', rok: 1990, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Dmuchawce, latawce, wiatr', wykonawca: 'Urszula', rok: 1991, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Baśka', wykonawca: 'Wilki', rok: 1992, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Makumba', wykonawca: 'Big Cyc', rok: 1993, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Człowiek z liściem', wykonawca: 'Elektryczne Gitary', rok: 1993, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Oprócz błękitnego nieba', wykonawca: 'Golden Life', rok: 1993, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Teksański', wykonawca: 'Hey', rok: 1993, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Zostawcie Titanica', wykonawca: 'De Mono', rok: 1994, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Lato', wykonawca: 'Formacja Nieżywych Schabuff', rok: 1994, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Moja i twoja nadzieja', wykonawca: 'Hey', rok: 1994, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Warszawa', wykonawca: 'T.Love', rok: 1994, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Scyzoryk', wykonawca: 'Liroy', rok: 1995, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Kobiety są gorące', wykonawca: 'Norbi', rok: 1995, gatunek: 'polskie', styl: 'dance' },
  { tytul: 'Przez twe oczy zielone', wykonawca: 'Akcent', rok: 1996, gatunek: 'polskie', styl: 'dance' },
  { tytul: 'Jesteś szalona', wykonawca: 'Boys', rok: 1996, gatunek: 'polskie', styl: 'dance' },
  { tytul: 'Sen', wykonawca: 'Edyta Bartosiewicz', rok: 1996, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Plus i minus', wykonawca: 'Kaliber 44', rok: 1996, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Zanim zrozumiesz', wykonawca: 'Varius Manx', rok: 1996, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Testosteron', wykonawca: 'Kayah', rok: 1997, gatunek: 'polskie', styl: 'rnb' },
  { tytul: 'Kiedy powiem sobie dość', wykonawca: 'O.N.A.', rok: 1998, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Prawy do lewego', wykonawca: 'Kayah i Bregović', rok: 1999, gatunek: 'polskie', styl: 'pop' },

  // ======================= LATA 2000. =======================
  // --- pop (16) ---
  { tytul: "Can't Get You Out of My Head", wykonawca: 'Kylie Minogue', rok: 2001, gatunek: 'pop' },
  { tytul: 'Whenever, Wherever', wykonawca: 'Shakira', rok: 2001, gatunek: 'pop' },
  { tytul: 'Complicated', wykonawca: 'Avril Lavigne', rok: 2002, gatunek: 'pop' },
  { tytul: 'Beautiful', wykonawca: 'Christina Aguilera', rok: 2002, gatunek: 'pop' },
  { tytul: 'Feel', wykonawca: 'Robbie Williams', rok: 2002, gatunek: 'pop' },
  { tytul: 'Toxic', wykonawca: 'Britney Spears', rok: 2003, gatunek: 'pop' },
  { tytul: 'Hey Ya!', wykonawca: 'OutKast', rok: 2003, gatunek: 'pop' },
  { tytul: 'Hollaback Girl', wykonawca: 'Gwen Stefani', rok: 2005, gatunek: 'pop' },
  { tytul: "You're Beautiful", wykonawca: 'James Blunt', rok: 2005, gatunek: 'pop' },
  { tytul: 'Smile', wykonawca: 'Lily Allen', rok: 2006, gatunek: 'pop' },
  { tytul: 'Say It Right', wykonawca: 'Nelly Furtado', rok: 2006, gatunek: 'pop' },
  { tytul: "Hips Don't Lie", wykonawca: 'Shakira', rok: 2006, gatunek: 'pop' },
  { tytul: 'Relax, Take It Easy', wykonawca: 'MIKA', rok: 2007, gatunek: 'pop' },
  { tytul: 'Umbrella', wykonawca: 'Rihanna', rok: 2007, gatunek: 'pop' },
  { tytul: 'I Kissed a Girl', wykonawca: 'Katy Perry', rok: 2008, gatunek: 'pop' },
  { tytul: 'So What', wykonawca: 'P!nk', rok: 2008, gatunek: 'pop' },
  // --- rock (23) ---
  { tytul: "It's My Life", wykonawca: 'Bon Jovi', rok: 2000, gatunek: 'rock' },
  { tytul: 'Yellow', wykonawca: 'Coldplay', rok: 2000, gatunek: 'rock' },
  { tytul: 'In the End', wykonawca: 'Linkin Park', rok: 2000, gatunek: 'rock' },
  { tytul: 'How You Remind Me', wykonawca: 'Nickelback', rok: 2001, gatunek: 'rock' },
  { tytul: 'Sonne', wykonawca: 'Rammstein', rok: 2001, gatunek: 'rock' },
  { tytul: 'In Too Deep', wykonawca: 'Sum 41', rok: 2001, gatunek: 'rock' },
  { tytul: 'Chop Suey!', wykonawca: 'System of a Down', rok: 2001, gatunek: 'rock' },
  { tytul: 'Last Nite', wykonawca: 'The Strokes', rok: 2001, gatunek: 'rock' },
  { tytul: 'Clocks', wykonawca: 'Coldplay', rok: 2002, gatunek: 'rock' },
  { tytul: 'By the Way', wykonawca: 'Red Hot Chili Peppers', rok: 2002, gatunek: 'rock' },
  { tytul: 'Bring Me to Life', wykonawca: 'Evanescence', rok: 2003, gatunek: 'rock' },
  { tytul: 'Numb', wykonawca: 'Linkin Park', rok: 2003, gatunek: 'rock' },
  { tytul: 'Seven Nation Army', wykonawca: 'The White Stripes', rok: 2003, gatunek: 'rock' },
  { tytul: 'Take Me Out', wykonawca: 'Franz Ferdinand', rok: 2004, gatunek: 'rock' },
  { tytul: 'Boulevard of Broken Dreams', wykonawca: 'Green Day', rok: 2004, gatunek: 'rock' },
  { tytul: 'Mr. Brightside', wykonawca: 'The Killers', rok: 2004, gatunek: 'rock' },
  { tytul: 'I Bet You Look Good on the Dancefloor', wykonawca: 'Arctic Monkeys', rok: 2005, gatunek: 'rock' },
  { tytul: 'Feel Good Inc.', wykonawca: 'Gorillaz', rok: 2005, gatunek: 'rock' },
  { tytul: 'Supermassive Black Hole', wykonawca: 'Muse', rok: 2006, gatunek: 'rock' },
  { tytul: 'Chasing Cars', wykonawca: 'Snow Patrol', rok: 2006, gatunek: 'rock' },
  { tytul: 'The Pretender', wykonawca: 'Foo Fighters', rok: 2007, gatunek: 'rock' },
  { tytul: 'Viva la Vida', wykonawca: 'Coldplay', rok: 2008, gatunek: 'rock' },
  { tytul: 'Sex on Fire', wykonawca: 'Kings of Leon', rok: 2008, gatunek: 'rock' },
  // --- rap / hip-hop (16) ---
  { tytul: 'Ms. Jackson', wykonawca: 'OutKast', rok: 2000, gatunek: 'rap' },
  { tytul: 'Get Ur Freak On', wykonawca: 'Missy Elliott', rok: 2001, gatunek: 'rap' },
  { tytul: 'Lose Yourself', wykonawca: 'Eminem', rok: 2002, gatunek: 'rap' },
  { tytul: 'Without Me', wykonawca: 'Eminem', rok: 2002, gatunek: 'rap' },
  { tytul: 'Hot in Herre', wykonawca: 'Nelly', rok: 2002, gatunek: 'rap' },
  { tytul: 'In da Club', wykonawca: '50 Cent', rok: 2003, gatunek: 'rap' },
  { tytul: '99 Problems', wykonawca: 'JAY-Z', rok: 2003, gatunek: 'rap' },
  { tytul: 'Where Is the Love?', wykonawca: 'The Black Eyed Peas', rok: 2003, gatunek: 'rap' },
  { tytul: 'My Band', wykonawca: 'D12', rok: 2004, gatunek: 'rap' },
  { tytul: "Drop It Like It's Hot", wykonawca: 'Snoop Dogg', rok: 2004, gatunek: 'rap' },
  { tytul: 'Gold Digger', wykonawca: 'Kanye West', rok: 2005, gatunek: 'rap' },
  { tytul: 'Smack That', wykonawca: 'Akon', rok: 2006, gatunek: 'rap' },
  { tytul: 'Low', wykonawca: 'Flo Rida', rok: 2007, gatunek: 'rap' },
  { tytul: 'Stronger', wykonawca: 'Kanye West', rok: 2007, gatunek: 'rap' },
  { tytul: 'Crank That (Soulja Boy)', wykonawca: 'Soulja Boy', rok: 2007, gatunek: 'rap' },
  { tytul: 'Lollipop', wykonawca: 'Lil Wayne', rok: 2008, gatunek: 'rap' },
  // --- dance / elektronika (20) ---
  { tytul: 'Around the World', wykonawca: 'ATC', rok: 2000, gatunek: 'dance' },
  { tytul: 'One More Time', wykonawca: 'Daft Punk', rok: 2000, gatunek: 'dance' },
  { tytul: 'Castles in the Sky', wykonawca: 'Ian Van Dahl', rok: 2000, gatunek: 'dance' },
  { tytul: 'Lady (Hear Me Tonight)', wykonawca: 'Modjo', rok: 2000, gatunek: 'dance' },
  { tytul: 'Harder, Better, Faster, Stronger', wykonawca: 'Daft Punk', rok: 2001, gatunek: 'dance' },
  { tytul: 'Satisfaction', wykonawca: 'Benny Benassi', rok: 2002, gatunek: 'dance' },
  { tytul: 'Heaven', wykonawca: 'DJ Sammy', rok: 2002, gatunek: 'dance' },
  { tytul: 'Moonlight Shadow', wykonawca: 'Groove Coverage', rok: 2002, gatunek: 'dance' },
  { tytul: 'Désenchantée', wykonawca: 'Kate Ryan', rok: 2002, gatunek: 'dance' },
  { tytul: 'Dragostea din tei', wykonawca: 'O-Zone', rok: 2003, gatunek: 'dance' },
  { tytul: 'Get Busy', wykonawca: 'Sean Paul', rok: 2003, gatunek: 'dance' },
  { tytul: 'Call on Me', wykonawca: 'Eric Prydz', rok: 2004, gatunek: 'dance' },
  { tytul: 'Love Generation', wykonawca: 'Bob Sinclar', rok: 2005, gatunek: 'dance' },
  { tytul: 'Everytime We Touch', wykonawca: 'Cascada', rok: 2005, gatunek: 'dance' },
  { tytul: 'Axel F', wykonawca: 'Crazy Frog', rok: 2005, gatunek: 'dance' },
  { tytul: 'Boten Anna', wykonawca: 'Basshunter', rok: 2006, gatunek: 'dance' },
  { tytul: 'Put Your Hands Up for Detroit', wykonawca: 'Fedde Le Grand', rok: 2006, gatunek: 'dance' },
  { tytul: 'Just Dance', wykonawca: 'Lady Gaga', rok: 2008, gatunek: 'dance' },
  { tytul: 'Poker Face', wykonawca: 'Lady Gaga', rok: 2008, gatunek: 'dance' },
  { tytul: 'When Love Takes Over', wykonawca: 'David Guetta', rok: 2009, gatunek: 'dance' },
  // --- r&b / soul (15) ---
  { tytul: '7 Days', wykonawca: 'Craig David', rok: 2000, gatunek: 'rnb' },
  { tytul: 'Survivor', wykonawca: "Destiny's Child", rok: 2001, gatunek: 'rnb' },
  { tytul: 'Family Affair', wykonawca: 'Mary J. Blige', rok: 2001, gatunek: 'rnb' },
  { tytul: 'Cry Me a River', wykonawca: 'Justin Timberlake', rok: 2002, gatunek: 'rnb' },
  { tytul: 'Crazy in Love', wykonawca: 'Beyoncé', rok: 2003, gatunek: 'rnb' },
  { tytul: 'Ordinary People', wykonawca: 'John Legend', rok: 2004, gatunek: 'rnb' },
  { tytul: 'Yeah!', wykonawca: 'Usher', rok: 2004, gatunek: 'rnb' },
  { tytul: 'Rehab', wykonawca: 'Amy Winehouse', rok: 2006, gatunek: 'rnb' },
  { tytul: 'Back to Black', wykonawca: 'Amy Winehouse', rok: 2006, gatunek: 'rnb' },
  { tytul: 'SexyBack', wykonawca: 'Justin Timberlake', rok: 2006, gatunek: 'rnb' },
  { tytul: 'So Sick', wykonawca: 'Ne-Yo', rok: 2006, gatunek: 'rnb' },
  { tytul: 'No One', wykonawca: 'Alicia Keys', rok: 2007, gatunek: 'rnb' },
  { tytul: 'Valerie', wykonawca: 'Mark Ronson feat. Amy Winehouse', rok: 2007, gatunek: 'rnb' },
  { tytul: "Don't Stop the Music", wykonawca: 'Rihanna', rok: 2007, gatunek: 'rnb' },
  { tytul: 'Single Ladies (Put a Ring on It)', wykonawca: 'Beyoncé', rok: 2008, gatunek: 'rnb' },
  // --- polskie (14) ---
  { tytul: 'A wszystko to... (bo ciebie kocham)', wykonawca: 'Ich Troje', rok: 2000, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Jestem Bogiem', wykonawca: 'Paktofonika', rok: 2000, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Długość dźwięku samotności', wykonawca: 'Myslovitz', rok: 2001, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Głucha noc', wykonawca: 'Peja', rok: 2001, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Do nieba, do piekła', wykonawca: 'Blue Café', rok: 2003, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Nigdy więcej nie tańcz ze mną', wykonawca: 'Ania Dąbrowska', rok: 2004, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Spadam', wykonawca: 'Coma', rok: 2004, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Pokolenie', wykonawca: 'Kombii', rok: 2004, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Żyletka', wykonawca: 'Strachy na Lachy', rok: 2004, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Zanim pójdę', wykonawca: 'Happysad', rok: 2005, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Katharsis', wykonawca: 'Doda', rok: 2007, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'A gdy jest już ciemno', wykonawca: 'Feel', rok: 2007, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Bezsenność', wykonawca: 'Video', rok: 2007, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Cicho', wykonawca: 'Ewa Farna', rok: 2008, gatunek: 'polskie', styl: 'pop' },

  // ======================= LATA 2010. =======================
  // --- pop (24) ---
  { tytul: 'Rolling in the Deep', wykonawca: 'Adele', rok: 2010, gatunek: 'pop' },
  { tytul: 'Just the Way You Are', wykonawca: 'Bruno Mars', rok: 2010, gatunek: 'pop' },
  { tytul: 'Somebody That I Used to Know', wykonawca: 'Gotye', rok: 2011, gatunek: 'pop' },
  { tytul: 'Call Me Maybe', wykonawca: 'Carly Rae Jepsen', rok: 2012, gatunek: 'pop' },
  { tytul: 'Let Her Go', wykonawca: 'Passenger', rok: 2012, gatunek: 'pop' },
  { tytul: 'Roar', wykonawca: 'Katy Perry', rok: 2013, gatunek: 'pop' },
  { tytul: 'Royals', wykonawca: 'Lorde', rok: 2013, gatunek: 'pop' },
  { tytul: 'Wrecking Ball', wykonawca: 'Miley Cyrus', rok: 2013, gatunek: 'pop' },
  { tytul: 'Counting Stars', wykonawca: 'OneRepublic', rok: 2013, gatunek: 'pop' },
  { tytul: 'Happy', wykonawca: 'Pharrell Williams', rok: 2013, gatunek: 'pop' },
  { tytul: 'Thinking Out Loud', wykonawca: 'Ed Sheeran', rok: 2014, gatunek: 'pop' },
  { tytul: 'Uptown Funk', wykonawca: 'Mark Ronson feat. Bruno Mars', rok: 2014, gatunek: 'pop' },
  { tytul: 'Stay With Me', wykonawca: 'Sam Smith', rok: 2014, gatunek: 'pop' },
  { tytul: 'Chandelier', wykonawca: 'Sia', rok: 2014, gatunek: 'pop' },
  { tytul: 'Shake It Off', wykonawca: 'Taylor Swift', rok: 2014, gatunek: 'pop' },
  { tytul: 'Blank Space', wykonawca: 'Taylor Swift', rok: 2014, gatunek: 'pop' },
  { tytul: 'Hello', wykonawca: 'Adele', rok: 2015, gatunek: 'pop' },
  { tytul: 'Sorry', wykonawca: 'Justin Bieber', rok: 2015, gatunek: 'pop' },
  { tytul: 'Havana', wykonawca: 'Camila Cabello', rok: 2017, gatunek: 'pop' },
  { tytul: 'New Rules', wykonawca: 'Dua Lipa', rok: 2017, gatunek: 'pop' },
  { tytul: 'Shape of You', wykonawca: 'Ed Sheeran', rok: 2017, gatunek: 'pop' },
  { tytul: 'Despacito', wykonawca: 'Luis Fonsi', rok: 2017, gatunek: 'pop' },
  { tytul: 'bad guy', wykonawca: 'Billie Eilish', rok: 2019, gatunek: 'pop' },
  { tytul: 'Dance Monkey', wykonawca: 'Tones and I', rok: 2019, gatunek: 'pop' },
  // --- rock (19) ---
  { tytul: 'Sail', wykonawca: 'AWOLNATION', rok: 2011, gatunek: 'rock' },
  { tytul: 'Walk', wykonawca: 'Foo Fighters', rok: 2011, gatunek: 'rock' },
  { tytul: 'Little Talks', wykonawca: 'Of Monsters and Men', rok: 2011, gatunek: 'rock' },
  { tytul: 'Lonely Boy', wykonawca: 'The Black Keys', rok: 2011, gatunek: 'rock' },
  { tytul: 'Radioactive', wykonawca: 'Imagine Dragons', rok: 2012, gatunek: 'rock' },
  { tytul: 'I Will Wait', wykonawca: 'Mumford & Sons', rok: 2012, gatunek: 'rock' },
  { tytul: 'Madness', wykonawca: 'Muse', rok: 2012, gatunek: 'rock' },
  { tytul: 'Ho Hey', wykonawca: 'The Lumineers', rok: 2012, gatunek: 'rock' },
  { tytul: 'Do I Wanna Know?', wykonawca: 'Arctic Monkeys', rok: 2013, gatunek: 'rock' },
  { tytul: 'Take Me to Church', wykonawca: 'Hozier', rok: 2013, gatunek: 'rock' },
  { tytul: 'Centuries', wykonawca: 'Fall Out Boy', rok: 2014, gatunek: 'rock' },
  { tytul: 'Figure It Out', wykonawca: 'Royal Blood', rok: 2014, gatunek: 'rock' },
  { tytul: 'Adventure of a Lifetime', wykonawca: 'Coldplay', rok: 2015, gatunek: 'rock' },
  { tytul: 'Stressed Out', wykonawca: 'Twenty One Pilots', rok: 2015, gatunek: 'rock' },
  { tytul: 'Way Down We Go', wykonawca: 'KALEO', rok: 2016, gatunek: 'rock' },
  { tytul: 'Heathens', wykonawca: 'Twenty One Pilots', rok: 2016, gatunek: 'rock' },
  { tytul: 'Believer', wykonawca: 'Imagine Dragons', rok: 2017, gatunek: 'rock' },
  { tytul: 'High Hopes', wykonawca: 'Panic! At The Disco', rok: 2018, gatunek: 'rock' },
  { tytul: 'Deutschland', wykonawca: 'Rammstein', rok: 2019, gatunek: 'rock' },
  // --- rap / hip-hop (19) ---
  { tytul: 'Runaway', wykonawca: 'Kanye West', rok: 2010, gatunek: 'rap' },
  { tytul: 'Thrift Shop', wykonawca: 'Macklemore & Ryan Lewis', rok: 2012, gatunek: 'rap' },
  { tytul: 'Rap God', wykonawca: 'Eminem', rok: 2013, gatunek: 'rap' },
  { tytul: 'Fancy', wykonawca: 'Iggy Azalea', rok: 2014, gatunek: 'rap' },
  { tytul: 'Anaconda', wykonawca: 'Nicki Minaj', rok: 2014, gatunek: 'rap' },
  { tytul: 'Hotline Bling', wykonawca: 'Drake', rok: 2015, gatunek: 'rap' },
  { tytul: 'Alright', wykonawca: 'Kendrick Lamar', rok: 2015, gatunek: 'rap' },
  { tytul: 'See You Again', wykonawca: 'Wiz Khalifa feat. Charlie Puth', rok: 2015, gatunek: 'rap' },
  { tytul: 'Bad and Boujee', wykonawca: 'Migos', rok: 2016, gatunek: 'rap' },
  { tytul: 'Congratulations', wykonawca: 'Post Malone', rok: 2016, gatunek: 'rap' },
  { tytul: 'Bodak Yellow', wykonawca: 'Cardi B', rok: 2017, gatunek: 'rap' },
  { tytul: 'HUMBLE.', wykonawca: 'Kendrick Lamar', rok: 2017, gatunek: 'rap' },
  { tytul: 'rockstar', wykonawca: 'Post Malone', rok: 2017, gatunek: 'rap' },
  { tytul: 'This Is America', wykonawca: 'Childish Gambino', rok: 2018, gatunek: 'rap' },
  { tytul: "God's Plan", wykonawca: 'Drake', rok: 2018, gatunek: 'rap' },
  { tytul: 'Sunflower', wykonawca: 'Post Malone & Swae Lee', rok: 2018, gatunek: 'rap' },
  { tytul: 'SICKO MODE', wykonawca: 'Travis Scott', rok: 2018, gatunek: 'rap' },
  { tytul: 'Old Town Road', wykonawca: 'Lil Nas X', rok: 2019, gatunek: 'rap' },
  { tytul: 'Circles', wykonawca: 'Post Malone', rok: 2019, gatunek: 'rap' },
  // --- dance / elektronika (23) ---
  { tytul: 'Levels', wykonawca: 'Avicii', rok: 2011, gatunek: 'dance' },
  { tytul: 'Titanium', wykonawca: 'David Guetta feat. Sia', rok: 2011, gatunek: 'dance' },
  { tytul: 'Party Rock Anthem', wykonawca: 'LMFAO', rok: 2011, gatunek: 'dance' },
  { tytul: 'Latch', wykonawca: 'Disclosure', rok: 2012, gatunek: 'dance' },
  { tytul: "Don't You Worry Child", wykonawca: 'Swedish House Mafia', rok: 2012, gatunek: 'dance' },
  { tytul: 'Clarity', wykonawca: 'Zedd', rok: 2012, gatunek: 'dance' },
  { tytul: 'Wake Me Up', wykonawca: 'Avicii', rok: 2013, gatunek: 'dance' },
  { tytul: 'Get Lucky', wykonawca: 'Daft Punk', rok: 2013, gatunek: 'dance' },
  { tytul: 'Animals', wykonawca: 'Martin Garrix', rok: 2013, gatunek: 'dance' },
  { tytul: 'Waves', wykonawca: 'Mr. Probz', rok: 2013, gatunek: 'dance' },
  { tytul: 'Timber', wykonawca: 'Pitbull feat. Kesha', rok: 2013, gatunek: 'dance' },
  { tytul: 'Summer', wykonawca: 'Calvin Harris', rok: 2014, gatunek: 'dance' },
  { tytul: 'Rather Be', wykonawca: 'Clean Bandit', rok: 2014, gatunek: 'dance' },
  { tytul: 'Firestone', wykonawca: 'Kygo', rok: 2014, gatunek: 'dance' },
  { tytul: 'Are You With Me', wykonawca: 'Lost Frequencies', rok: 2014, gatunek: 'dance' },
  { tytul: 'Cheerleader', wykonawca: 'OMI', rok: 2014, gatunek: 'dance' },
  { tytul: 'Prayer in C', wykonawca: 'Robin Schulz', rok: 2014, gatunek: 'dance' },
  { tytul: 'Faded', wykonawca: 'Alan Walker', rok: 2015, gatunek: 'dance' },
  { tytul: 'Ocean Drive', wykonawca: 'Duke Dumont', rok: 2015, gatunek: 'dance' },
  { tytul: 'Lean On', wykonawca: 'Major Lazer', rok: 2015, gatunek: 'dance' },
  { tytul: 'This Is What You Came For', wykonawca: 'Calvin Harris feat. Rihanna', rok: 2016, gatunek: 'dance' },
  { tytul: 'Closer', wykonawca: 'The Chainsmokers', rok: 2016, gatunek: 'dance' },
  { tytul: "Don't Start Now", wykonawca: 'Dua Lipa', rok: 2019, gatunek: 'dance' },
  // --- r&b / soul (12) ---
  { tytul: 'Thinkin Bout You', wykonawca: 'Frank Ocean', rok: 2012, gatunek: 'rnb' },
  { tytul: 'Adorn', wykonawca: 'Miguel', rok: 2012, gatunek: 'rnb' },
  { tytul: 'Diamonds', wykonawca: 'Rihanna', rok: 2012, gatunek: 'rnb' },
  { tytul: "Can't Feel My Face", wykonawca: 'The Weeknd', rok: 2015, gatunek: 'rnb' },
  { tytul: 'Formation', wykonawca: 'Beyoncé', rok: 2016, gatunek: 'rnb' },
  { tytul: "That's What I Like", wykonawca: 'Bruno Mars', rok: 2016, gatunek: 'rnb' },
  { tytul: 'Redbone', wykonawca: 'Childish Gambino', rok: 2016, gatunek: 'rnb' },
  { tytul: 'Get You', wykonawca: 'Daniel Caesar', rok: 2016, gatunek: 'rnb' },
  { tytul: 'Location', wykonawca: 'Khalid', rok: 2016, gatunek: 'rnb' },
  { tytul: 'Work', wykonawca: 'Rihanna', rok: 2016, gatunek: 'rnb' },
  { tytul: 'Starboy', wykonawca: 'The Weeknd', rok: 2016, gatunek: 'rnb' },
  { tytul: 'The Weekend', wykonawca: 'SZA', rok: 2017, gatunek: 'rnb' },
  // --- polskie (19) ---
  { tytul: 'Varsovie', wykonawca: 'Brodka', rok: 2010, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Skrzydlate ręce', wykonawca: 'Enej', rok: 2011, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Małe rzeczy', wykonawca: 'Sylwia Grzeszczak', rok: 2011, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Napraw', wykonawca: 'LemON', rok: 2012, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Trójkąty i kwadraty', wykonawca: 'Dawid Podsiadło', rok: 2013, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'W dobrą stronę', wykonawca: 'Dawid Podsiadło', rok: 2013, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Nic do stracenia', wykonawca: 'Mrozu', rok: 2013, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Thank You Very Much', wykonawca: 'Margaret', rok: 2014, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Mississippi w ogniu', wykonawca: 'Organek', rok: 2014, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Mój dom', wykonawca: 'Kortez', rok: 2015, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Bądź duży', wykonawca: 'Natalia Nykiel', rok: 2015, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Naucz mnie', wykonawca: 'Sarsa', rok: 2015, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Malinowy chruśniak', wykonawca: 'Daria Zawiałow', rok: 2017, gatunek: 'polskie', styl: 'rock' },
  { tytul: '6 zer', wykonawca: 'Taco Hemingway', rok: 2017, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Małomiasteczkowy', wykonawca: 'Dawid Podsiadło', rok: 2018, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Nie ma fal', wykonawca: 'Dawid Podsiadło & Taco Hemingway', rok: 2018, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Dziś późno pójdę spać', wykonawca: 'Kwiat Jabłoni', rok: 2019, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Patointeligencja', wykonawca: 'Mata', rok: 2019, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Melodia', wykonawca: 'sanah', rok: 2019, gatunek: 'polskie', styl: 'pop' },

  // ======================= LATA 2020. =======================
  // --- pop (20) ---
  { tytul: 'Say So', wykonawca: 'Doja Cat', rok: 2020, gatunek: 'pop' },
  { tytul: 'Levitating', wykonawca: 'Dua Lipa', rok: 2020, gatunek: 'pop' },
  { tytul: 'Physical', wykonawca: 'Dua Lipa', rok: 2020, gatunek: 'pop' },
  { tytul: 'Heat Waves', wykonawca: 'Glass Animals', rok: 2020, gatunek: 'pop' },
  { tytul: 'Watermelon Sugar', wykonawca: 'Harry Styles', rok: 2020, gatunek: 'pop' },
  { tytul: 'Blinding Lights', wykonawca: 'The Weeknd', rok: 2020, gatunek: 'pop' },
  { tytul: 'Happier Than Ever', wykonawca: 'Billie Eilish', rok: 2021, gatunek: 'pop' },
  { tytul: 'Cold Heart (PNAU Remix)', wykonawca: 'Elton John & Dua Lipa', rok: 2021, gatunek: 'pop' },
  { tytul: 'abcdefu', wykonawca: 'GAYLE', rok: 2021, gatunek: 'pop' },
  { tytul: 'drivers license', wykonawca: 'Olivia Rodrigo', rok: 2021, gatunek: 'pop' },
  { tytul: 'good 4 u', wykonawca: 'Olivia Rodrigo', rok: 2021, gatunek: 'pop' },
  { tytul: 'As It Was', wykonawca: 'Harry Styles', rok: 2022, gatunek: 'pop' },
  { tytul: 'Stick Season', wykonawca: 'Noah Kahan', rok: 2022, gatunek: 'pop' },
  { tytul: 'Unholy', wykonawca: 'Sam Smith & Kim Petras', rok: 2022, gatunek: 'pop' },
  { tytul: 'Anti-Hero', wykonawca: 'Taylor Swift', rok: 2022, gatunek: 'pop' },
  { tytul: 'Flowers', wykonawca: 'Miley Cyrus', rok: 2023, gatunek: 'pop' },
  { tytul: 'Beautiful Things', wykonawca: 'Benson Boone', rok: 2024, gatunek: 'pop' },
  { tytul: 'BIRDS OF A FEATHER', wykonawca: 'Billie Eilish', rok: 2024, gatunek: 'pop' },
  { tytul: 'Good Luck, Babe!', wykonawca: 'Chappell Roan', rok: 2024, gatunek: 'pop' },
  { tytul: 'Espresso', wykonawca: 'Sabrina Carpenter', rok: 2024, gatunek: 'pop' },
  // --- rock (12) ---
  { tytul: 'The Adults Are Talking', wykonawca: 'The Strokes', rok: 2020, gatunek: 'rock' },
  { tytul: 'Higher Power', wykonawca: 'Coldplay', rok: 2021, gatunek: 'rock' },
  { tytul: 'My Universe', wykonawca: 'Coldplay & BTS', rok: 2021, gatunek: 'rock' },
  { tytul: 'Enemy', wykonawca: 'Imagine Dragons', rok: 2021, gatunek: 'rock' },
  { tytul: 'Beggin', wykonawca: 'Måneskin', rok: 2021, gatunek: 'rock' },
  { tytul: 'ZITTI E BUONI', wykonawca: 'Måneskin', rok: 2021, gatunek: 'rock' },
  { tytul: 'Chaise Longue', wykonawca: 'Wet Leg', rok: 2021, gatunek: 'rock' },
  { tytul: 'Bones', wykonawca: 'Imagine Dragons', rok: 2022, gatunek: 'rock' },
  { tytul: 'Zeit', wykonawca: 'Rammstein', rok: 2022, gatunek: 'rock' },
  { tytul: 'Rescued', wykonawca: 'Foo Fighters', rok: 2023, gatunek: 'rock' },
  { tytul: 'Too Sweet', wykonawca: 'Hozier', rok: 2024, gatunek: 'rock' },
  { tytul: 'The Emptiness Machine', wykonawca: 'Linkin Park', rok: 2024, gatunek: 'rock' },
  // --- rap / hip-hop (10) ---
  { tytul: 'WAP', wykonawca: 'Cardi B feat. Megan Thee Stallion', rok: 2020, gatunek: 'rap' },
  { tytul: 'Savage', wykonawca: 'Megan Thee Stallion', rok: 2020, gatunek: 'rap' },
  { tytul: 'Industry Baby', wykonawca: 'Lil Nas X', rok: 2021, gatunek: 'rap' },
  { tytul: 'MONTERO (Call Me By Your Name)', wykonawca: 'Lil Nas X', rok: 2021, gatunek: 'rap' },
  { tytul: 'Tití Me Preguntó', wykonawca: 'Bad Bunny', rok: 2022, gatunek: 'rap' },
  { tytul: 'Rich Flex', wykonawca: 'Drake & 21 Savage', rok: 2022, gatunek: 'rap' },
  { tytul: 'Super Freaky Girl', wykonawca: 'Nicki Minaj', rok: 2022, gatunek: 'rap' },
  { tytul: 'Paint The Town Red', wykonawca: 'Doja Cat', rok: 2023, gatunek: 'rap' },
  { tytul: 'First Person Shooter', wykonawca: 'Drake feat. J. Cole', rok: 2023, gatunek: 'rap' },
  { tytul: 'Not Like Us', wykonawca: 'Kendrick Lamar', rok: 2024, gatunek: 'rap' },
  // --- dance / elektronika (11) ---
  { tytul: 'Dákiti', wykonawca: 'Bad Bunny & Jhay Cortez', rok: 2020, gatunek: 'dance' },
  { tytul: 'Head & Heart', wykonawca: 'Joel Corry feat. MNEK', rok: 2020, gatunek: 'dance' },
  { tytul: 'Jerusalema', wykonawca: 'Master KG', rok: 2020, gatunek: 'dance' },
  { tytul: 'Bad Habits', wykonawca: 'Ed Sheeran', rok: 2021, gatunek: 'dance' },
  { tytul: 'Pepas', wykonawca: 'Farruko', rok: 2021, gatunek: 'dance' },
  { tytul: 'Where Are You Now', wykonawca: 'Lost Frequencies & Calum Scott', rok: 2021, gatunek: 'dance' },
  { tytul: 'Rasputin', wykonawca: 'Majestic & Boney M.', rok: 2021, gatunek: 'dance' },
  { tytul: 'Ferrari', wykonawca: 'James Hype & Miggy Dela Rosa', rok: 2022, gatunek: 'dance' },
  { tytul: "I Ain't Worried", wykonawca: 'OneRepublic', rok: 2022, gatunek: 'dance' },
  { tytul: 'Miracle', wykonawca: 'Calvin Harris & Ellie Goulding', rok: 2023, gatunek: 'dance' },
  { tytul: 'Padam Padam', wykonawca: 'Kylie Minogue', rok: 2023, gatunek: 'dance' },
  // --- r&b / soul (10) ---
  { tytul: 'Good Days', wykonawca: 'SZA', rok: 2020, gatunek: 'rnb' },
  { tytul: 'Save Your Tears', wykonawca: 'The Weeknd', rok: 2020, gatunek: 'rnb' },
  { tytul: 'Essence', wykonawca: 'Wizkid feat. Tems', rok: 2020, gatunek: 'rnb' },
  { tytul: 'Peaches', wykonawca: 'Justin Bieber', rok: 2021, gatunek: 'rnb' },
  { tytul: 'Leave The Door Open', wykonawca: 'Silk Sonic', rok: 2021, gatunek: 'rnb' },
  { tytul: 'CUFF IT', wykonawca: 'Beyoncé', rok: 2022, gatunek: 'rnb' },
  { tytul: 'Calm Down', wykonawca: 'Rema', rok: 2022, gatunek: 'rnb' },
  { tytul: 'Kill Bill', wykonawca: 'SZA', rok: 2022, gatunek: 'rnb' },
  { tytul: 'Snooze', wykonawca: 'SZA', rok: 2022, gatunek: 'rnb' },
  { tytul: 'Lose Control', wykonawca: 'Teddy Swims', rok: 2023, gatunek: 'rnb' },
  // --- polskie (9) ---
  { tytul: 'Za krótki sen', wykonawca: 'Daria Zawiałow', rok: 2020, gatunek: 'polskie', styl: 'rock' },
  { tytul: 'Szampan', wykonawca: 'sanah', rok: 2020, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Ale jazz!', wykonawca: 'sanah & Vito Bambino', rok: 2020, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Puste kieszenie', wykonawca: 'Sobel', rok: 2020, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Wypijmy za błędy', wykonawca: 'Igo', rok: 2021, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Kiss cam', wykonawca: 'Mata', rok: 2021, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Kolońska i szlugi', wykonawca: 'sanah', rok: 2021, gatunek: 'polskie', styl: 'pop' },
  { tytul: 'Szklanki', wykonawca: 'Young Leosia', rok: 2021, gatunek: 'polskie', styl: 'rap' },
  { tytul: 'Mori', wykonawca: 'Dawid Podsiadło', rok: 2022, gatunek: 'polskie', styl: 'pop' },

  // Tu dopisuj świeżynki (2025, 2026) i to, czego brakuje — jedna linijka na utwór.
];
