/* ==========================================================================
   Gacha Miast — katalog miast
   Jeden wiersz to jedno miasto:
     [ nazwa, kraj, flaga, kontynent, ludność w tysiącach, po co tam jechać ]

   Zasady doboru:
   • ok. 100 tys. mieszkańców w górę (miasto albo jego aglomeracja) — chodzi
     o miejsca, które mają czym zająć na weekend, nie o przysiółki;
   • każde miasto musi mieć powód, żeby tam pojechać — stąd ostatnia kolumna;
   • nazwy polskie tam, gdzie polska nazwa jest w powszechnym użyciu
     (Monachium, Lizbona, Erywań), oryginalne tam, gdzie polskiej nie ma;
   • liczby ludności są zaokrąglone i orientacyjne — służą skali, nie statystyce;
   • pomijamy miasta, do których w tej chwili nie należy jechać.

   Kontynenty: eu Europa · az Azja · af Afryka · na Ameryka Płn. ·
               sa Ameryka Płd. · oc Australia i Oceania
   ========================================================================== */

const KONTYNENTY = [
  // `gdzie` to forma do zdania „… miast na B w Azji" — bez niej licznik puli
  // brzmiałby jak telegram.
  { id: 'eu', nazwa: 'Europa',       krotko: 'Europa',   gdzie: 'w Europie',       emoji: '🏰' },
  { id: 'az', nazwa: 'Azja',         krotko: 'Azja',     gdzie: 'w Azji',          emoji: '⛩️' },
  { id: 'af', nazwa: 'Afryka',       krotko: 'Afryka',   gdzie: 'w Afryce',        emoji: '🦁' },
  { id: 'na', nazwa: 'Ameryka Płn.', krotko: 'Am. Płn.', gdzie: 'w Ameryce Płn.',  emoji: '🗽' },
  { id: 'sa', nazwa: 'Ameryka Płd.', krotko: 'Am. Płd.', gdzie: 'w Ameryce Płd.',  emoji: '🏔️' },
  { id: 'oc', nazwa: 'Oceania',      krotko: 'Oceania',  gdzie: 'w Oceanii',       emoji: '🏄' },
];

const MIASTA = [
  // ---------------------------------------------------------------- Europa
  ['Amsterdam', 'Holandia', '🇳🇱', 'eu', 920, 'Kanały, Rijksmuseum, Van Gogh i rowery zamiast aut'],
  ['Ateny', 'Grecja', '🇬🇷', 'eu', 3100, 'Akropol nad miastem i tawerny w Place'],
  ['Antwerpia', 'Belgia', '🇧🇪', 'eu', 530, 'Katedra Rubensa, diamenty i najładniejszy dworzec Europy'],
  ['Alicante', 'Hiszpania', '🇪🇸', 'eu', 340, 'Zamek Santa Bárbara nad plażą i deptak z palmami'],
  ['Aarhus', 'Dania', '🇩🇰', 'eu', 290, 'Tęczowa panorama na dachu ARoS i skansen Den Gamle By'],
  ['Augsburg', 'Niemcy', '🇩🇪', 'eu', 300, 'Renesansowe fontanny i Fuggerei — najstarsze osiedle socjalne świata'],
  ['Barcelona', 'Hiszpania', '🇪🇸', 'eu', 1600, 'Sagrada Família, Gaudí na każdym rogu i plaża w mieście'],
  ['Berlin', 'Niemcy', '🇩🇪', 'eu', 3700, 'Wyspa Muzeów, mur, techno i najtańsze stolice śniadania'],
  ['Budapeszt', 'Węgry', '🇭🇺', 'eu', 1750, 'Parlament nad Dunajem, łaźnie termalne i ruin-bary'],
  ['Bruksela', 'Belgia', '🇧🇪', 'eu', 1200, 'Grand Place, Atomium, komiksy i frytki z majonezem'],
  ['Bukareszt', 'Rumunia', '🇷🇴', 'eu', 1800, 'Gigantyczny Pałac Parlamentu i secesyjne uliczki Lipscani'],
  ['Bergen', 'Norwegia', '🇳🇴', 'eu', 290, 'Bryggen z drewnianych spichlerzy i brama do fiordów'],
  ['Bilbao', 'Hiszpania', '🇪🇸', 'eu', 350, 'Guggenheim Gehry’ego i pintxos w Starym Mieście'],
  ['Bolonia', 'Włochy', '🇮🇹', 'eu', 390, 'Czterdzieści kilometrów podcieni i kuchnia, od której zaczyna się Włochy'],
  ['Bratysława', 'Słowacja', '🇸🇰', 'eu', 480, 'Zamek nad Dunajem i najkrótsza droga do Wiednia'],
  ['Brno', 'Czechy', '🇨🇿', 'eu', 400, 'Wila Tugendhat, kawiarnie i studencki luz bez tłumów Pragi'],
  ['Bordeaux', 'Francja', '🇫🇷', 'eu', 1200, 'Kamienna starówka z listy UNESCO i winnice tuż za miastem'],
  ['Belgrad', 'Serbia', '🇷🇸', 'eu', 1400, 'Twierdza Kalemegdan i noc, która nigdy się nie kończy'],
  ['Brugia', 'Belgia', '🇧🇪', 'eu', 120, 'Średniowieczne miasto na kanałach, czekolada i piwo trapistów'],
  ['Bydgoszcz', 'Polska', '🇵🇱', 'eu', 330, 'Wyspa Młyńska, Wenecja Bydgoska i secesyjne kamienice'],
  ['Białystok', 'Polska', '🇵🇱', 'eu', 295, 'Pałac Branickich i baza wypadowa w Podlasie'],
  ['Bari', 'Włochy', '🇮🇹', 'eu', 320, 'Stare Miasto, gdzie orecchiette suszą się na ulicy'],
  ['Braga', 'Portugalia', '🇵🇹', 'eu', 190, 'Schody Bom Jesus do Monte i najstarsza katedra kraju'],
  ['Cardiff', 'Walia', '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'eu', 365, 'Zamek w środku miasta, zatoka i rugby na Millennium Stadium'],
  ['Cluj-Napoca', 'Rumunia', '🇷🇴', 'eu', 325, 'Studenckie serce Transylwanii i festiwale wielkości miasta'],
  ['Konstanca', 'Rumunia', '🇷🇴', 'eu', 280, 'Rzymskie mozaiki i secesyjne kasyno nad Morzem Czarnym'],
  ['Katania', 'Włochy', '🇮🇹', 'eu', 300, 'Barok z czarnej lawy u stóp Etny i targ rybny Pescheria'],
  ['Kordoba', 'Hiszpania', '🇪🇸', 'eu', 325, 'Meczet-katedra Mezquita i dziedzińce tonące w kwiatach'],
  ['Cork', 'Irlandia', '🇮🇪', 'eu', 220, 'Targ English Market i najlepszy punkt startu na klify Moher'],
  ['Coimbra', 'Portugalia', '🇵🇹', 'eu', 105, 'Barokowa biblioteka Joanina i uniwersytet z XIII wieku'],
  ['Dublin', 'Irlandia', '🇮🇪', 'eu', 1200, 'Trinity College, Book of Kells i pub na każdej przecznicy'],
  ['Drezno', 'Niemcy', '🇩🇪', 'eu', 560, 'Zwinger, Frauenkirche i galeria z Madonną Sykstyńską'],
  ['Düsseldorf', 'Niemcy', '🇩🇪', 'eu', 620, 'Altstadt zwana najdłuższym barem świata i architektura Gehry’ego'],
  ['Dortmund', 'Niemcy', '🇩🇪', 'eu', 590, 'Żółta Ściana na Signal Iduna Park i poprzemysłowe muzea Zagłębia Ruhry'],
  ['Debreczyn', 'Węgry', '🇭🇺', 'eu', 200, 'Wielki Kościół Kalwiński i las termalny Nagyerdő'],
  ['Delft', 'Holandia', '🇳🇱', 'eu', 105, 'Miasto Vermeera, niebieska ceramika i kanały bez tłumów'],
  ['Edynburg', 'Szkocja', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'eu', 520, 'Zamek na wulkanie, Royal Mile i sierpniowy Fringe'],
  ['Essen', 'Niemcy', '🇩🇪', 'eu', 580, 'Kopalnia Zollverein — cud architektury przemysłowej z listy UNESCO'],
  ['Eindhoven', 'Holandia', '🇳🇱', 'eu', 245, 'Stolica designu, Philips Museum i Glow Festival'],
  ['Erfurt', 'Niemcy', '🇩🇪', 'eu', 215, 'Krämerbrücke — most zabudowany domami i średniowieczna starówka'],
  ['Florencja', 'Włochy', '🇮🇹', 'eu', 380, 'Uffizi, Dawid, kopuła Brunelleschiego i Ponte Vecchio'],
  ['Frankfurt nad Menem', 'Niemcy', '🇩🇪', 'eu', 770, 'Szklana panorama nad muzealnym nabrzeżem Menu'],
  ['Fryburg Bryzgowijski', 'Niemcy', '🇩🇪', 'eu', 235, 'Kanaliki Bächle w bruku i brama do Schwarzwaldu'],
  ['Ferrara', 'Włochy', '🇮🇹', 'eu', 130, 'Zamek na wodzie i renesansowe miasto, po którym jeździ się rowerem'],
  ['Genewa', 'Szwajcaria', '🇨🇭', 'eu', 200, 'Jezioro z fontanną Jet d’Eau, CERN i Mont Blanc na horyzoncie'],
  ['Gdańsk', 'Polska', '🇵🇱', 'eu', 490, 'Długi Targ, Żuraw, bursztyn i Westerplatte'],
  ['Genua', 'Włochy', '🇮🇹', 'eu', 560, 'Pałace Rolli, największe akwarium Europy i focaccia'],
  ['Glasgow', 'Szkocja', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'eu', 635, 'Mackintosh, galeria Kelvingrove i najlepsza scena muzyczna Szkocji'],
  ['Göteborg', 'Szwecja', '🇸🇪', 'eu', 590, 'Kanały, Liseberg i szkiery na wyciągnięcie promu'],
  ['Grenada', 'Hiszpania', '🇪🇸', 'eu', 230, 'Alhambra nad miastem, Albaicín i darmowe tapas'],
  ['Graz', 'Austria', '🇦🇹', 'eu', 300, 'Kopiec Schlossberg, dachy starówki i kosmiczny Kunsthaus'],
  ['Gandawa', 'Belgia', '🇧🇪', 'eu', 265, 'Ołtarz Gandawski, zamek Gravensteen i studenckie kanały'],
  ['Getynga', 'Niemcy', '🇩🇪', 'eu', 120, 'Miasto noblistów, mury z alejką i pomnik Gęsiareczki'],
  ['Hamburg', 'Niemcy', '🇩🇪', 'eu', 1900, 'Elbphilharmonie, Speicherstadt i port większy niż niejedno miasto'],
  ['Helsinki', 'Finlandia', '🇫🇮', 'eu', 660, 'Kościół w skale, sauny miejskie i design na każdym rogu'],
  ['Hanower', 'Niemcy', '🇩🇪', 'eu', 540, 'Ogrody Herrenhausen i czerwona nitka prowadząca po zabytkach'],
  ['Haga', 'Holandia', '🇳🇱', 'eu', 560, 'Mauritshuis z Dziewczyną z perłą i plaża Scheveningen'],
  ['Heidelberg', 'Niemcy', '🇩🇪', 'eu', 160, 'Ruiny zamku nad Neckarem i najstarszy uniwersytet Niemiec'],
  ['Haarlem', 'Holandia', '🇳🇱', 'eu', 165, 'Frans Hals Museum i Amsterdam w wersji kameralnej'],
  ['Innsbruck', 'Austria', '🇦🇹', 'eu', 130, 'Złoty Daszek, skocznia Bergisel i Alpy zaczynające się na końcu ulicy'],
  ['Iwano-Frankiwsk', 'Ukraina', '🇺🇦', 'eu', 230, 'Secesyjna starówka i brama w Karpaty Wschodnie'],
  ['Jassy', 'Rumunia', '🇷🇴', 'eu', 290, 'Pałac Kultury i najstarsza stolica Mołdawii rumuńskiej'],
  ['Jena', 'Niemcy', '🇩🇪', 'eu', 110, 'Miasto Zeissa, planetarium i doliny Turyngii'],
  ['Kraków', 'Polska', '🇵🇱', 'eu', 800, 'Wawel, Sukiennice, Kazimierz i najwięcej zabytków w kraju'],
  ['Kolonia', 'Niemcy', '🇩🇪', 'eu', 1080, 'Katedra nad Renem, muzeum czekolady i karnawał'],
  ['Kopenhaga', 'Dania', '🇩🇰', 'eu', 660, 'Nyhavn, Tivoli, rowery i restauracje z gwiazdkami'],
  ['Kijów', 'Ukraina', '🇺🇦', 'eu', 3000, 'Sobór Sofijski, Ławra Peczerska i strome zbocza nad Dnieprem'],
  ['Kowno', 'Litwa', '🇱🇹', 'eu', 300, 'Modernizm z listy UNESCO i widok ze wzgórza Aleksota'],
  ['Kłajpeda', 'Litwa', '🇱🇹', 'eu', 160, 'Pruska starówka i prom na Mierzeję Kurońską'],
  ['Karlsruhe', 'Niemcy', '🇩🇪', 'eu', 310, 'Miasto-wachlarz wokół pałacu i centrum sztuki mediów ZKM'],
  ['Kilonia', 'Niemcy', '🇩🇪', 'eu', 250, 'Fiord, regaty Kieler Woche i śluzy Kanału Kilońskiego'],
  ['Kazań', 'Rosja', '🇷🇺', 'eu', 1300, 'Biały kreml z meczetem Kul Szarif — Wschód i Zachód w jednym murze'],
  ['Lizbona', 'Portugalia', '🇵🇹', 'eu', 2800, 'Tramwaj 28, Belém, fado i pastéis de nata prosto z pieca'],
  ['Londyn', 'Anglia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'eu', 9000, 'British Museum, Tate, parki i darmowe muzea na tydzień'],
  ['Lyon', 'Francja', '🇫🇷', 'eu', 1400, 'Traboules Starego Lyonu i stolica francuskiej kuchni'],
  ['Lipsk', 'Niemcy', '🇩🇪', 'eu', 620, 'Bach w Thomaskirche, Spinnerei i Berlin sprzed dwudziestu lat'],
  ['Lublana', 'Słowenia', '🇸🇮', 'eu', 295, 'Mosty Plečnika, zamek nad miastem i deptak nad Lublanicą'],
  ['Lublin', 'Polska', '🇵🇱', 'eu', 335, 'Zamek z kaplicą Trójcy Świętej i najlepiej zachowana starówka wschodu'],
  ['Łódź', 'Polska', '🇵🇱', 'eu', 655, 'Piotrkowska, Księży Młyn i fabryki zamienione w muzea'],
  ['Linz', 'Austria', '🇦🇹', 'eu', 210, 'Ars Electronica Center i Dunaj z widokiem na Pöstlingberg'],
  ['Leeds', 'Anglia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'eu', 800, 'Wiktoriańskie pasaże handlowe i brama do Yorkshire Dales'],
  ['Liverpool', 'Anglia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'eu', 500, 'Beatlesi, Albert Dock i Anfield'],
  ['Lozanna', 'Szwajcaria', '🇨🇭', 'eu', 140, 'Muzeum Olimpijskie nad Jeziorem Genewskim i winnice Lavaux'],
  ['Lwów', 'Ukraina', '🇺🇦', 'eu', 720, 'Rynek, opera i kawiarnie z austro-węgierskim rodowodem'],
  ['Las Palmas', 'Hiszpania', '🇪🇸', 'eu', 380, 'Plaża Las Canteras i wiecznie wiosenna Gran Canaria'],
  ['Madryt', 'Hiszpania', '🇪🇸', 'eu', 3300, 'Prado, Reina Sofía, Retiro i noc, która zaczyna się o północy'],
  ['Mediolan', 'Włochy', '🇮🇹', 'eu', 1400, 'Katedra z dachem do zwiedzania, Ostatnia Wieczerza i moda'],
  ['Monachium', 'Niemcy', '🇩🇪', 'eu', 1500, 'Ogródki piwne, Pinakoteki, Oktoberfest i Alpy godzinę dalej'],
  ['Marsylia', 'Francja', '🇫🇷', 'eu', 870, 'Stary Port, MuCEM i calanques z turkusową wodą'],
  ['Manchester', 'Anglia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'eu', 560, 'Northern Quarter, muzeum nauki i dwa wielkie kluby piłkarskie'],
  ['Malaga', 'Hiszpania', '🇪🇸', 'eu', 580, 'Muzeum Picassa, alkazaba i najcieplejsza zima Europy'],
  ['Mińsk', 'Białoruś', '🇧🇾', 'eu', 2000, 'Monumentalny socrealizm w skali, jakiej nie ma nigdzie indziej'],
  ['Malmö', 'Szwecja', '🇸🇪', 'eu', 360, 'Turning Torso, plaże Ribersborg i most do Kopenhagi'],
  ['Mostar', 'Bośnia i Hercegowina', '🇧🇦', 'eu', 105, 'Stary Most, skoczkowie do Neretwy i osmańska starówka'],
  ['Modena', 'Włochy', '🇮🇹', 'eu', 185, 'Ocet balsamiczny, muzeum Ferrari i romańska katedra'],
  ['Montpellier', 'Francja', '🇫🇷', 'eu', 300, 'Place de la Comédie, studenci i Morze Śródziemne pod bokiem'],
  ['Neapol', 'Włochy', '🇮🇹', 'eu', 920, 'Pizza z pieca, podziemia i Pompeje z Wezuwiuszem obok'],
  ['Nicea', 'Francja', '🇫🇷', 'eu', 340, 'Promenade des Anglais, Stare Miasto i Lazurowe Wybrzeże'],
  ['Norymberga', 'Niemcy', '🇩🇪', 'eu', 520, 'Zamek cesarski, jarmark bożonarodzeniowy i muzeum procesów'],
  ['Nantes', 'Francja', '🇫🇷', 'eu', 320, 'Mechaniczny słoń Les Machines i zamek książąt Bretanii'],
  ['Nikozja', 'Cypr', '🇨🇾', 'eu', 340, 'Ostatnia podzielona stolica Europy — przejście przez linię ONZ'],
  ['Nowy Sad', 'Serbia', '🇷🇸', 'eu', 370, 'Twierdza Petrovaradin i festiwal EXIT nad Dunajem'],
  ['Oslo', 'Norwegia', '🇳🇴', 'eu', 710, 'Muzeum Muncha, opera po której się chodzi i Vigelandsparken'],
  ['Odessa', 'Ukraina', '🇺🇦', 'eu', 1000, 'Schody Potiomkinowskie, opera i nadmorski bulwar'],
  ['Ostrawa', 'Czechy', '🇨🇿', 'eu', 285, 'Dolní Vítkovice — huta zamieniona w scenę i Colours of Ostrava'],
  ['Oksford', 'Anglia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'eu', 155, 'Kolegia, Bodleian Library i punt po rzece Cherwell'],
  ['Olsztyn', 'Polska', '🇵🇱', 'eu', 170, 'Zamek Kopernika i jedenaście jezior w granicach miasta'],
  ['Oviedo', 'Hiszpania', '🇪🇸', 'eu', 220, 'Przedromańskie kościółki i cydr lany z wysokości ramienia'],
  ['Paryż', 'Francja', '🇫🇷', 'eu', 11000, 'Luwr, wieża Eiffla, Marais i bulwary Sekwany'],
  ['Praga', 'Czechy', '🇨🇿', 'eu', 1300, 'Most Karola, Hradczany, zegar astronomiczny i piwo taniej niż woda'],
  ['Porto', 'Portugalia', '🇵🇹', 'eu', 1700, 'Ribeira nad Douro, porto z piwnic Gai i księgarnia Lello'],
  ['Palermo', 'Włochy', '🇮🇹', 'eu', 650, 'Kaplica Palatyńska, targi Ballarò i sycylijskie street foody'],
  ['Poznań', 'Polska', '🇵🇱', 'eu', 540, 'Koziołki na ratuszu, Ostrów Tumski i Stary Browar'],
  ['Płowdiw', 'Bułgaria', '🇧🇬', 'eu', 345, 'Rzymski teatr wciąż w użyciu i dzielnica artystów Kapana'],
  ['Pilzno', 'Czechy', '🇨🇿', 'eu', 175, 'Browar Pilsner Urquell i największa synagoga w Europie Środkowej'],
  ['Palma de Mallorca', 'Hiszpania', '🇪🇸', 'eu', 420, 'Katedra La Seu nad zatoką i góry Serra de Tramuntana'],
  ['Padwa', 'Włochy', '🇮🇹', 'eu', 210, 'Freski Giotta w Cappella degli Scrovegni i najstarszy ogród botaniczny'],
  ['Pecz', 'Węgry', '🇭🇺', 'eu', 140, 'Meczet zamieniony w kościół i ceramika Zsolnay'],
  ['Rzym', 'Włochy', '🇮🇹', 'eu', 2800, 'Koloseum, Watykan, Forum i fontanny na każdym placu'],
  ['Rotterdam', 'Holandia', '🇳🇱', 'eu', 660, 'Markthal, domy-sześciany i architektura zamiast starówki'],
  ['Ryga', 'Łotwa', '🇱🇻', 'eu', 615, 'Największy zbiór secesji w Europie i hale targowe w hangarach'],
  ['Rejkiawik', 'Islandia', '🇮🇸', 'eu', 140, 'Hallgrímskirkja, Harpa i wypad po zorzę albo na Złoty Krąg'],
  ['Rennes', 'Francja', '🇫🇷', 'eu', 220, 'Domy z muru pruskiego i brama do Mont-Saint-Michel'],
  ['Ratyzbona', 'Niemcy', '🇩🇪', 'eu', 155, 'Nietknięta wojną starówka i kamienny most z XII wieku'],
  ['Rawenna', 'Włochy', '🇮🇹', 'eu', 160, 'Bizantyjskie mozaiki, jakich nie ma nawet w Stambule'],
  ['Rijeka', 'Chorwacja', '🇭🇷', 'eu', 110, 'Port z austro-węgierskim rozmachem i zamek Trsat'],
  ['Sztokholm', 'Szwecja', '🇸🇪', 'eu', 980, 'Gamla Stan, muzeum Vasa i miasto rozłożone na czternastu wyspach'],
  ['Sewilla', 'Hiszpania', '🇪🇸', 'eu', 690, 'Alkazar, Giralda, flamenco i Plaza de España'],
  ['Split', 'Chorwacja', '🇭🇷', 'eu', 160, 'Pałac Dioklecjana, w którym wciąż się mieszka, i promy na wyspy'],
  ['Sofia', 'Bułgaria', '🇧🇬', 'eu', 1300, 'Cerkiew Aleksandra Newskiego i Witosza tuż za miastem'],
  ['Salzburg', 'Austria', '🇦🇹', 'eu', 155, 'Mozart, twierdza Hohensalzburg i alpejskie tło'],
  ['Strasburg', 'Francja', '🇫🇷', 'eu', 290, 'Katedra z zegarem, La Petite France i Parlament Europejski'],
  ['Stuttgart', 'Niemcy', '🇩🇪', 'eu', 630, 'Muzea Mercedesa i Porsche, winnice w granicach miasta'],
  ['Sarajewo', 'Bośnia i Hercegowina', '🇧🇦', 'eu', 275, 'Baščaršija, ślady 1914 i 1984 roku, kawa po bośniacku'],
  ['Saloniki', 'Grecja', '🇬🇷', 'eu', 325, 'Biała Wieża, bizantyjskie mury i najlepsze jedzenie w Grecji'],
  ['Szczecin', 'Polska', '🇵🇱', 'eu', 390, 'Wały Chrobrego, filharmonia-lodowiec i gwiaździsty układ ulic'],
  ['Stambuł', 'Turcja', '🇹🇷', 'eu', 15500, 'Hagia Sophia, Błękitny Meczet i Bosfor dzielący kontynenty'],
  ['Saragossa', 'Hiszpania', '🇪🇸', 'eu', 680, 'Bazylika del Pilar nad Ebro i mudéjarska architektura'],
  ['San Sebastián', 'Hiszpania', '🇪🇸', 'eu', 190, 'Zatoka La Concha i najwięcej gwiazdek Michelin na mieszkańca'],
  ['Sankt Petersburg', 'Rosja', '🇷🇺', 'eu', 5400, 'Ermitaż, kanały i białe noce'],
  ['Turyn', 'Włochy', '🇮🇹', 'eu', 870, 'Mole Antonelliana, Muzeum Egipskie i Alpy na horyzoncie'],
  ['Tuluza', 'Francja', '🇫🇷', 'eu', 500, 'Różowe miasto, Airbus i Kanał Południowy'],
  ['Tallin', 'Estonia', '🇪🇪', 'eu', 450, 'Średniowieczne mury i cyfrowa republika w środku'],
  ['Triest', 'Włochy', '🇮🇹', 'eu', 200, 'Piazza Unità nad morzem, zamek Miramare i kawiarnie literackie'],
  ['Trydent', 'Włochy', '🇮🇹', 'eu', 120, 'Zamek Buonconsiglio i Dolomity za rogatkami'],
  ['Tampere', 'Finlandia', '🇫🇮', 'eu', 245, 'Ceglane fabryki między dwoma jeziorami i muzeum Muminków'],
  ['Trondheim', 'Norwegia', '🇳🇴', 'eu', 210, 'Katedra Nidaros i kolorowe spichlerze nad rzeką Nidelvą'],
  ['Tirana', 'Albania', '🇦🇱', 'eu', 560, 'Pomalowane bloki, bunkry-muzea i najtańsza stolica Europy'],
  ['Toruń', 'Polska', '🇵🇱', 'eu', 195, 'Gotyckie miasto Kopernika, pierniki i Krzywa Wieża'],
  ['Timișoara', 'Rumunia', '🇷🇴', 'eu', 300, 'Habsburskie place, secesja i pierwsze elektryczne latarnie Europy'],
  ['Utrecht', 'Holandia', '🇳🇱', 'eu', 365, 'Kanały z nabrzeżami piętro niżej i wieża Dom'],
  ['Uppsala', 'Szwecja', '🇸🇪', 'eu', 175, 'Katedra, Linneusz i kurhany starej Uppsali'],
  ['Ulm', 'Niemcy', '🇩🇪', 'eu', 130, 'Najwyższa wieża kościelna świata i dzielnica rybaków'],
  ['Użhorod', 'Ukraina', '🇺🇦', 'eu', 115, 'Zamek nad Użem i najdłuższa aleja kwitnących sakur w Europie'],
  ['Valladolid', 'Hiszpania', '🇪🇸', 'eu', 300, 'Rzeźba polichromowana, dom Cervantesa i wina Ribera del Duero'],
  ['Vigo', 'Hiszpania', '🇪🇸', 'eu', 295, 'Owoce morza z Rías Baixas i prom na Wyspy Ciés'],
  ['Vitoria-Gasteiz', 'Hiszpania', '🇪🇸', 'eu', 255, 'Zielona stolica Europy i średniowieczne wzgórze w środku'],
  ['Warszawa', 'Polska', '🇵🇱', 'eu', 1860, 'Odbudowana starówka, Muzeum Powstania i Wisła z plażami'],
  ['Wiedeń', 'Austria', '🇦🇹', 'eu', 2000, 'Schönbrunn, Hofburg, Klimt i kawiarnie z listy UNESCO'],
  ['Wilno', 'Litwa', '🇱🇹', 'eu', 590, 'Barokowa starówka, Ostra Brama i republika Užupis'],
  ['Wrocław', 'Polska', '🇵🇱', 'eu', 675, 'Rynek, Ostrów Tumski, Hala Stulecia i krasnale'],
  ['Werona', 'Włochy', '🇮🇹', 'eu', 260, 'Rzymska Arena z operą i balkon Julii'],
  ['Walencja', 'Hiszpania', '🇪🇸', 'eu', 800, 'Miasto Sztuki i Nauki, paella u źródła i park w dawnym korycie rzeki'],
  ['Wenecja', 'Włochy', '🇮🇹', 'eu', 255, 'Kanały, Bazylika św. Marka i Biennale'],
  ['Warna', 'Bułgaria', '🇧🇬', 'eu', 340, 'Najstarsze złoto świata w muzeum i nadmorski park'],
  ['Wiesbaden', 'Niemcy', '🇩🇪', 'eu', 280, 'Uzdrowisko z kasynem i kolejka na Neroberg'],
  ['York', 'Anglia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'eu', 155, 'Mury miejskie, York Minster i wikińskie Jorvik'],
  ['Zurych', 'Szwajcaria', '🇨🇭', 'eu', 440, 'Jezioro, Kunsthaus, Bahnhofstrasse i Alpy w zasięgu pociągu'],
  ['Zagrzeb', 'Chorwacja', '🇭🇷', 'eu', 770, 'Górne Miasto, Muzeum Zerwanych Związków i adwent roku'],
  ['Zaporoże', 'Ukraina', '🇺🇦', 'eu', 710, 'Wyspa Chortyca — kolebka Kozaczyzny na Dnieprze'],

  // ------------------------------------------------------------------ Azja
  ['Amman', 'Jordania', '🇯🇴', 'az', 4000, 'Rzymski teatr, cytadela i najbliżej stąd do Petry'],
  ['Ahmadabad', 'Indie', '🇮🇳', 'az', 8000, 'Aszram Gandhiego i studnie schodkowe pod miastem'],
  ['Astana', 'Kazachstan', '🇰🇿', 'az', 1300, 'Futurystyczna stolica postawiona na stepie od zera'],
  ['Ałmaty', 'Kazachstan', '🇰🇿', 'az', 2000, 'Góry Zailijskie nad miastem i lodowisko Miedieu'],
  ['Ankara', 'Turcja', '🇹🇷', 'az', 5700, 'Muzeum Cywilizacji Anatolijskich i mauzoleum Atatürka'],
  ['Agra', 'Indie', '🇮🇳', 'az', 1600, 'Tadż Mahal o wschodzie słońca i Czerwony Fort'],
  ['Bangkok', 'Tajlandia', '🇹🇭', 'az', 10500, 'Wielki Pałac, świątynie, kanały i jedzenie z ulicy'],
  ['Bengaluru', 'Indie', '🇮🇳', 'az', 13000, 'Pałac Tipu Sultana, ogrody Lalbagh i indyjskie Krzemowe Miasto'],
  ['Bursa', 'Turcja', '🇹🇷', 'az', 2100, 'Pierwsza stolica Osmanów pod górą Uludağ'],
  ['Busan', 'Korea Południowa', '🇰🇷', 'az', 3400, 'Kolorowa dzielnica Gamcheon, plaże i targ rybny Jagalchi'],
  ['Bandung', 'Indonezja', '🇮🇩', 'az', 2500, 'Wulkan Tangkuban Perahu i art déco w chłodnych górach Jawy'],
  ['Bejrut', 'Liban', '🇱🇧', 'az', 2400, 'Corniche nad morzem i warstwy pięciu cywilizacji pod miastem'],
  ['Baku', 'Azerbejdżan', '🇦🇿', 'az', 2300, 'Wieże Płomienia nad średniowiecznym İçərişəhər'],
  ['Batumi', 'Gruzja', '🇬🇪', 'az', 170, 'Nadmorski bulwar, dziwaczne wieżowce i wjazd w Adżarię'],
  ['Chengdu', 'Chiny', '🇨🇳', 'az', 16000, 'Baza pand, herbaciarnie i najostrzejsza kuchnia Chin'],
  ['Chennai', 'Indie', '🇮🇳', 'az', 11000, 'Świątynie drawidyjskie i najdłuższa miejska plaża Indii'],
  ['Chiang Mai', 'Tajlandia', '🇹🇭', 'az', 1000, 'Setki świątyń w starym mieście i festiwal lampionów'],
  ['Kolombo', 'Sri Lanka', '🇱🇰', 'az', 750, 'Kolonialny Fort, targ Pettah i start pociągu w góry'],
  ['Cebu', 'Filipiny', '🇵🇭', 'az', 970, 'Krzyż Magellana i rekiny wielorybie kilka godzin dalej'],
  ['Delhi', 'Indie', '🇮🇳', 'az', 32000, 'Czerwony Fort, Humajun, Qutb Minar i chaos Chandni Chowk'],
  ['Dubaj', 'Zjednoczone Emiraty Arabskie', '🇦🇪', 'az', 3600, 'Burdż Chalifa, suki nad zatoką i pustynia godzinę dalej'],
  ['Doha', 'Katar', '🇶🇦', 'az', 1200, 'Muzeum Sztuki Islamu, suk Wakif i panorama West Bay'],
  ['Dhaka', 'Bangladesz', '🇧🇩', 'az', 10000, 'Różowy pałac Ahsan Manzil i rzeczny port Sadarghat'],
  ['Da Nang', 'Wietnam', '🇻🇳', 'az', 1200, 'Złoty Most na dłoniach, plaża i Hội An tuż obok'],
  ['Dżakarta', 'Indonezja', '🇮🇩', 'az', 10600, 'Kota Tua, Monas i punkt startu na całą Jawę'],
  ['Dalian', 'Chiny', '🇨🇳', 'az', 4400, 'Nadmorskie bulwary i rosyjsko-japońskie dziedzictwo w architekturze'],
  ['Erywań', 'Armenia', '🇦🇲', 'az', 1100, 'Kaskada, rękopisy Matenadaranu i Ararat na horyzoncie'],
  ['Fukuoka', 'Japonia', '🇯🇵', 'az', 1600, 'Budki yatai z ramenem i najstarsza świątynia zen w Japonii'],
  ['George Town', 'Malezja', '🇲🇾', 'az', 800, 'Street art na Penangu i najlepsze uliczne jedzenie Malezji'],
  ['Gyeongju', 'Korea Południowa', '🇰🇷', 'az', 250, 'Kurhany królów Silli i grota Seokguram — muzeum bez ścian'],
  ['Hongkong', 'Chiny', '🇭🇰', 'az', 7500, 'Victoria Peak, dim sum i wieżowce wyrastające z dżungli'],
  ['Hanoi', 'Wietnam', '🇻🇳', 'az', 8000, 'Stare Miasto 36 ulic, jezioro Hoan Kiem i pho na śniadanie'],
  ['Hiroszima', 'Japonia', '🇯🇵', 'az', 1200, 'Kopuła Pokoju i brama torii na wodzie w Miyajimie'],
  ['Hajdarabad', 'Indie', '🇮🇳', 'az', 10000, 'Charminar, fort Golkonda i biryani'],
  ['Ho Chi Minh', 'Wietnam', '🇻🇳', 'az', 9300, 'Kolonialne centrum, tunele Củ Chi i motocykle w rytmie miasta'],
  ['Hangzhou', 'Chiny', '🇨🇳', 'az', 12000, 'Jezioro Zachodnie — chiński ideał krajobrazu — i plantacje herbaty'],
  ['Isfahan', 'Iran', '🇮🇷', 'az', 2200, 'Plac Naqsz-e Dżahan, mosty na Zajande i błękitne kopuły'],
  ['Islamabad', 'Pakistan', '🇵🇰', 'az', 1100, 'Meczet Faisala pod wzgórzami Margalla'],
  ['Incheon', 'Korea Południowa', '🇰🇷', 'az', 3000, 'Największe chińskie miasto Korei i wyspy Morza Żółtego'],
  ['Izmir', 'Turcja', '🇹🇷', 'az', 4400, 'Nadmorska Kordon i antyczny Efez pod bokiem'],
  ['Jerozolima', 'Izrael', '🇮🇱', 'az', 970, 'Ściana Płaczu, Bazylika Grobu i Kopuła na Skale w jednym murze'],
  ['Jaipur', 'Indie', '🇮🇳', 'az', 4000, 'Różowe Miasto, Hawa Mahal i fort Amber'],
  ['Kioto', 'Japonia', '🇯🇵', 'az', 1460, 'Fushimi Inari, Złoty Pawilon, gejsze w Gion i bambusowy las'],
  ['Kanton', 'Chiny', '🇨🇳', 'az', 15000, 'Dim sum u źródła, wyspa Shamian i wieża Canton Tower'],
  ['Katmandu', 'Nepal', '🇳🇵', 'az', 1500, 'Durbar Square, stupa Bodnath i brama w Himalaje'],
  ['Kuala Lumpur', 'Malezja', '🇲🇾', 'az', 8000, 'Petronas Towers, jaskinie Batu i trzy kuchnie w jednym mieście'],
  ['Kalkuta', 'Indie', '🇮🇳', 'az', 15000, 'Victoria Memorial, tramwaje i literacka stolica Indii'],
  ['Kobe', 'Japonia', '🇯🇵', 'az', 1500, 'Port między górami a morzem, wołowina i onseny Arima'],
  ['Kaohsiung', 'Tajwan', '🇹🇼', 'az', 2700, 'Lotosowy Staw z pagodami Smoka i Tygrysa, targi nocne'],
  ['Kanazawa', 'Japonia', '🇯🇵', 'az', 465, 'Ogród Kenroku-en, dzielnica gejsz i złoto płatkowe'],
  ['Kaszgar', 'Chiny', '🇨🇳', 'az', 700, 'Ujgurskie stare miasto i niedzielny bazar na Jedwabnym Szlaku'],
  ['Kuching', 'Malezja', '🇲🇾', 'az', 700, 'Borneo, orangutany w Semenggoh i długie domy nad rzeką'],
  ['Kandy', 'Sri Lanka', '🇱🇰', 'az', 125, 'Świątynia Zęba Buddy nad jeziorem i pociąg przez plantacje'],
  ['Lhasa', 'Chiny', '🇨🇳', 'az', 500, 'Pałac Potala i Jokhang na dachu świata'],
  ['Lahaur', 'Pakistan', '🇵🇰', 'az', 13000, 'Meczet Badśahi, fort i ogrody Shalimar z czasów Mogołów'],
  ['Mumbaj', 'Indie', '🇮🇳', 'az', 21000, 'Brama Indii, Marine Drive, Bollywood i wyspa Elefanta'],
  ['Manila', 'Filipiny', '🇵🇭', 'az', 14000, 'Intramuros, mury Fort Santiago i zachody nad zatoką'],
  ['Makau', 'Chiny', '🇲🇴', 'az', 680, 'Ruiny św. Pawła, portugalskie uliczki i kasyna'],
  ['Maskat', 'Oman', '🇴🇲', 'az', 1500, 'Meczet Sułtana Kabusa, suk Mutrah i wadi za miastem'],
  ['Malakka', 'Malezja', '🇲🇾', 'az', 500, 'Holenderski plac, Jonker Street i kuchnia Peranakan'],
  ['Mandalaj', 'Mjanma', '🇲🇲', 'az', 1200, 'Tekowy most U Bein i wzgórze z widokiem na Irawadi'],
  ['Nagoja', 'Japonia', '🇯🇵', 'az', 2300, 'Zamek ze złotymi delfinami i muzeum Toyoty'],
  ['Nara', 'Japonia', '🇯🇵', 'az', 360, 'Wielki Budda w Tōdai-ji i jelenie kłaniające się za ciastko'],
  ['Nagasaki', 'Japonia', '🇯🇵', 'az', 410, 'Park Pokoju, Glover Garden i chrześcijańska historia Japonii'],
  ['Osaka', 'Japonia', '🇯🇵', 'az', 2700, 'Dōtonbori w neonach, zamek i takoyaki'],
  ['Osz', 'Kirgistan', '🇰🇬', 'az', 320, 'Święta góra Sulejmana i najstarszy bazar Azji Środkowej'],
  ['Pekin', 'Chiny', '🇨🇳', 'az', 21500, 'Zakazane Miasto, Wielki Mur i hutongi'],
  ['Phnom Penh', 'Kambodża', '🇰🇭', 'az', 2300, 'Srebrna Pagoda, Pałac Królewski i pamięć o Czerwonych Khmerach'],
  ['Pusan', 'Korea Południowa', '🇰🇷', 'az', 3400, 'Świątynia Haedong Yonggungsa na klifie nad morzem'],
  ['Qingdao', 'Chiny', '🇨🇳', 'az', 5300, 'Niemiecka starówka, browar Tsingtao i plaże Morza Żółtego'],
  ['Rijad', 'Arabia Saudyjska', '🇸🇦', 'az', 7700, 'Twierdza Masmak, Edge of the World i pustynne wydmy'],
  ['Rangun', 'Mjanma', '🇲🇲', 'az', 5400, 'Złota pagoda Szwedagon i kolonialne śródmieście'],
  ['Seul', 'Korea Południowa', '🇰🇷', 'az', 9600, 'Pałac Gyeongbokgung, Bukchon, K-pop i nocne targi'],
  ['Szanghaj', 'Chiny', '🇨🇳', 'az', 24000, 'Bund, Pudong, ogród Yuyuan i wodne miasteczka obok'],
  ['Singapur', 'Singapur', '🇸🇬', 'az', 5900, 'Gardens by the Bay, hawker centres i trzy kultury na wyspie'],
  ['Sapporo', 'Japonia', '🇯🇵', 'az', 1970, 'Festiwal śniegu, ramen miso i najlepszy puder Hokkaido'],
  ['Samarkanda', 'Uzbekistan', '🇺🇿', 'az', 550, 'Registan, Szahi Zinda i błękit Jedwabnego Szlaku'],
  ['Suzhou', 'Chiny', '🇨🇳', 'az', 7500, 'Klasyczne ogrody z listy UNESCO i kanały zwane Wenecją Wschodu'],
  ['Sziraz', 'Iran', '🇮🇷', 'az', 1600, 'Różowy meczet Nasir al-Molk i Persepolis godzinę dalej'],
  ['Tokio', 'Japonia', '🇯🇵', 'az', 14000, 'Shibuya, Asakusa, targ Toyosu i Fuji w pogodny dzień'],
  ['Tajpej', 'Tajwan', '🇹🇼', 'az', 2600, 'Taipei 101, targi nocne i gorące źródła Beitou'],
  ['Teheran', 'Iran', '🇮🇷', 'az', 9000, 'Pałac Golestan, klejnoty koronne i Elburs nad miastem'],
  ['Taszkent', 'Uzbekistan', '🇺🇿', 'az', 2900, 'Metro jak podziemne muzeum i bazar Chorsu'],
  ['Tbilisi', 'Gruzja', '🇬🇪', 'az', 1200, 'Stare Miasto z łaźniami siarkowymi, twierdza Narikala i wino'],
  ['Tel Awiw', 'Izrael', '🇮🇱', 'az', 470, 'Białe Miasto Bauhausu, plaże i stara Jafa'],
  ['Tiencin', 'Chiny', '🇨🇳', 'az', 13500, 'Europejskie koncesje nad rzeką i diabelski młyn na moście'],
  ['Ułan Bator', 'Mongolia', '🇲🇳', 'az', 1600, 'Klasztor Gandan i step z jurtami tuż za rogatkami'],
  ['Urumczi', 'Chiny', '🇨🇳', 'az', 4000, 'Wielki Bazar i jezioro Tianchi w Górach Niebiańskich'],
  ['Udaipur', 'Indie', '🇮🇳', 'az', 475, 'Pałace na jeziorze Pichola — najbardziej romantyczne miasto Radżastanu'],
  ['Wientian', 'Laos', '🇱🇦', 'az', 950, 'Pha That Luang, francuskie bagietki i leniwy Mekong'],
  ['Waranasi', 'Indie', '🇮🇳', 'az', 1200, 'Ghaty nad Gangesem i wieczorna ceremonia ognia'],
  ['Wuhan', 'Chiny', '🇨🇳', 'az', 11000, 'Wieża Żółtego Żurawia i jezioro Wschodnie większe od miasta'],
  ['Xi’an', 'Chiny', '🇨🇳', 'az', 9600, 'Terakotowa Armia, mury miejskie i dzielnica muzułmańska'],
  ['Xiamen', 'Chiny', '🇨🇳', 'az', 4300, 'Wyspa Gulangyu bez samochodów i kolonialne wille'],
  ['Yogyakarta', 'Indonezja', '🇮🇩', 'az', 420, 'Borobudur i Prambanan o świcie, batik i kraton sułtana'],
  ['Jazd', 'Iran', '🇮🇷', 'az', 530, 'Glinane miasto z wieżami wiatrowymi i świątynią ognia'],
  ['Jokohama', 'Japonia', '🇯🇵', 'az', 3700, 'Największe Chinatown Japonii i nabrzeże Minato Mirai'],

  // ---------------------------------------------------------------- Afryka
  ['Aleksandria', 'Egipt', '🇪🇬', 'af', 5200, 'Biblioteka Alexandrina, cytadela Kajtbaja i katakumby'],
  ['Addis Abeba', 'Etiopia', '🇪🇹', 'af', 3900, 'Lucy w Muzeum Narodowym i najlepsza kawa świata u źródła'],
  ['Akra', 'Ghana', '🇬🇭', 'af', 2500, 'Fort Jamestown, targ Makola i plaże Zatoki Gwinejskiej'],
  ['Agadir', 'Maroko', '🇲🇦', 'af', 600, 'Dziesięć kilometrów plaży i kasba nad zatoką'],
  ['Antananarywa', 'Madagaskar', '🇲🇬', 'af', 1300, 'Pałac Rova na wzgórzu i brama do lemurowych parków'],
  ['Asuan', 'Egipt', '🇪🇬', 'af', 290, 'Nubijskie wioski, świątynia Philae i felukami po Nilu'],
  ['Casablanca', 'Maroko', '🇲🇦', 'af', 3400, 'Meczet Hassana II nad oceanem i art déco śródmieścia'],
  ['Dakar', 'Senegal', '🇸🇳', 'af', 1200, 'Wyspa Gorée, Pomnik Odrodzenia i muzyka mbalax'],
  ['Dar es Salaam', 'Tanzania', '🇹🇿', 'af', 5400, 'Targ rybny, plaże i prom na Zanzibar'],
  ['Durban', 'Republika Południowej Afryki', '🇿🇦', 'af', 3900, 'Golden Mile, indyjskie targi i ciepły Ocean Indyjski'],
  ['Fez', 'Maroko', '🇲🇦', 'af', 1200, 'Medyna bez samochodów, garbarnie i najstarszy uniwersytet świata'],
  ['Gizeh', 'Egipt', '🇪🇬', 'af', 4400, 'Piramidy i Sfinks na skraju miasta'],
  ['Harare', 'Zimbabwe', '🇿🇼', 'af', 1500, 'Ogrody botaniczne i baza wypadowa w Wielkie Zimbabwe'],
  ['Hurghada', 'Egipt', '🇪🇬', 'af', 250, 'Rafy Morza Czerwonego i nurkowanie przez cały rok'],
  ['Johannesburg', 'Republika Południowej Afryki', '🇿🇦', 'af', 5800, 'Muzeum Apartheidu, Soweto i Kolebka Ludzkości'],
  ['Kair', 'Egipt', '🇪🇬', 'af', 10000, 'Muzeum Egipskie, Chan el-Chalili i piramidy za rzeką'],
  ['Kapsztad', 'Republika Południowej Afryki', '🇿🇦', 'af', 4700, 'Góra Stołowa, Przylądek Dobrej Nadziei i winnice'],
  ['Kigali', 'Rwanda', '🇷🇼', 'af', 1200, 'Najczystsza stolica Afryki i goryle w Parku Wulkanów'],
  ['Kampala', 'Uganda', '🇺🇬', 'af', 1700, 'Groby królów Buganda i Nil wypływający z Jeziora Wiktorii'],
  ['Lagos', 'Nigeria', '🇳🇬', 'af', 15000, 'Afrobeats, galeria Nike Art i plaże Lekki'],
  ['Luksor', 'Egipt', '🇪🇬', 'af', 500, 'Karnak, Dolina Królów i balon nad Nilem o świcie'],
  ['Lusaka', 'Zambia', '🇿🇲', 'af', 3300, 'Targi rzemiosła i punkt startu nad Wodospad Wiktorii'],
  ['Marrakesz', 'Maroko', '🇲🇦', 'af', 1000, 'Dżemaa el-Fna, riady, suki i Atlas na horyzoncie'],
  ['Maputo', 'Mozambik', '🇲🇿', 'af', 1100, 'Portugalski modernizm, dworzec Eiffla i owoce morza'],
  ['Mombasa', 'Kenia', '🇰🇪', 'af', 1200, 'Fort Jesus, suahilijska starówka i plaże Diani'],
  ['Meknes', 'Maroko', '🇲🇦', 'af', 630, 'Brama Bab Mansur i rzymskie Volubilis obok'],
  ['Nairobi', 'Kenia', '🇰🇪', 'af', 5000, 'Park narodowy w granicach miasta i żyrafy z bliska'],
  ['Oran', 'Algieria', '🇩🇿', 'af', 950, 'Fort Santa Cruz nad zatoką i kolebka muzyki raï'],
  ['Ouagadougou', 'Burkina Faso', '🇧🇫', 'af', 2500, 'FESPACO — największy festiwal filmowy Afryki'],
  ['Pretoria', 'Republika Południowej Afryki', '🇿🇦', 'af', 2500, 'Union Buildings i fioletowe jakarandy w październiku'],
  ['Port Louis', 'Mauritius', '🇲🇺', 'af', 150, 'Kreolski targ, Caudan Waterfront i wulkaniczne wnętrze wyspy'],
  ['Rabat', 'Maroko', '🇲🇦', 'af', 580, 'Kasba Udajów nad oceanem i wieża Hassana'],
  ['Sfaks', 'Tunezja', '🇹🇳', 'af', 330, 'Medyna bez turystów i wypad na Wyspy Kerkena'],
  ['Susa', 'Tunezja', '🇹🇳', 'af', 250, 'Ribat, medyna z listy UNESCO i plaże Zatoki Hammamet'],
  ['Tunis', 'Tunezja', '🇹🇳', 'af', 1100, 'Medyna, Bardo z mozaikami i Kartagina za miastem'],
  ['Tanger', 'Maroko', '🇲🇦', 'af', 1200, 'Kasba nad Cieśniną Gibraltarską i jaskinie Herkulesa'],
  ['Windhuk', 'Namibia', '🇳🇦', 'af', 450, 'Niemiecka architektura na pustyni i start w wydmy Sossusvlei'],
  ['Zanzibar', 'Tanzania', '🇹🇿', 'af', 220, 'Stone Town, targ przypraw i plaże na wschodzie wyspy'],
  ['Livingstone', 'Zambia', '🇿🇲', 'af', 180, 'Wodospad Wiktorii z bliska i Zambezi o zachodzie'],

  // -------------------------------------------------------- Ameryka Północna
  ['Austin', 'Stany Zjednoczone', '🇺🇸', 'na', 970, 'Muzyka na żywo przy 6th Street, food trucki i SXSW'],
  ['Atlanta', 'Stany Zjednoczone', '🇺🇸', 'na', 6000, 'Centrum Martina Luthera Kinga i największe akwarium półkuli'],
  ['Acapulco', 'Meksyk', '🇲🇽', 'na', 680, 'Skoczkowie z klifu La Quebrada i zatoka w kształcie podkowy'],
  ['Aguascalientes', 'Meksyk', '🇲🇽', 'na', 950, 'Muzeum Posady i kwietniowa Feria de San Marcos'],
  ['Boston', 'Stany Zjednoczone', '🇺🇸', 'na', 4900, 'Freedom Trail, Harvard za rzeką i najstarsze puby USA'],
  ['Baltimore', 'Stany Zjednoczone', '🇺🇸', 'na', 570, 'Inner Harbor, muzeum Poego i kraby z Zatoki Chesapeake'],
  ['Chicago', 'Stany Zjednoczone', '🇺🇸', 'na', 2700, 'Architektura z rejsu po rzece, Art Institute i blues'],
  ['Cancún', 'Meksyk', '🇲🇽', 'na', 890, 'Karaibskie plaże, cenoty i Chichén Itzá w zasięgu'],
  ['Calgary', 'Kanada', '🇨🇦', 'na', 1400, 'Stampede, kowbojski Zachód i Banff półtorej godziny dalej'],
  ['Charleston', 'Stany Zjednoczone', '🇺🇸', 'na', 155, 'Pastelowe kamienice Rainbow Row i plantacje z alejami dębów'],
  ['Denver', 'Stany Zjednoczone', '🇺🇸', 'na', 715, 'Brama w Góry Skaliste i amfiteatr Red Rocks'],
  ['Detroit', 'Stany Zjednoczone', '🇺🇸', 'na', 630, 'Motown, murale i największe muzeum przemysłu w Ameryce'],
  ['Dallas', 'Stany Zjednoczone', '🇺🇸', 'na', 1300, 'Dealey Plaza, dzielnica sztuki i teksański rozmach'],
  ['Edmonton', 'Kanada', '🇨🇦', 'na', 1050, 'West Edmonton Mall i festiwale przez całe lato'],
  ['Filadelfia', 'Stany Zjednoczone', '🇺🇸', 'na', 1580, 'Dzwon Wolności, schody Rocky’ego i murale na całym mieście'],
  ['Guadalajara', 'Meksyk', '🇲🇽', 'na', 1400, 'Mariachi, murale Orozco i tequila z sąsiedniego miasteczka'],
  ['Gwatemala', 'Gwatemala', '🇬🇹', 'na', 1000, 'Muzeum Popol Vuh i Antigua z wulkanami godzinę dalej'],
  ['Guanajuato', 'Meksyk', '🇲🇽', 'na', 195, 'Kolorowe domy na zboczach i ulice biegnące pod miastem'],
  ['Hawana', 'Kuba', '🇨🇺', 'na', 2100, 'Habana Vieja, Malecón i amerykańskie auta z lat 50.'],
  ['Houston', 'Stany Zjednoczone', '🇺🇸', 'na', 2300, 'Centrum kosmiczne NASA i dzielnica muzeów'],
  ['Honolulu', 'Stany Zjednoczone', '🇺🇸', 'na', 350, 'Waikiki, Diamond Head i Pearl Harbor'],
  ['Halifax', 'Kanada', '🇨🇦', 'na', 450, 'Cytadela nad portem, historia Titanica i homary'],
  ['Indianapolis', 'Stany Zjednoczone', '🇺🇸', 'na', 880, 'Tor Indy 500 i największe muzeum dziecięce świata'],
  ['Kansas City', 'Stany Zjednoczone', '🇺🇸', 'na', 510, 'Jazz w 18th & Vine, barbecue i więcej fontann niż w Rzymie'],
  ['Kingston', 'Jamajka', '🇯🇲', 'na', 670, 'Muzeum Boba Marleya i Góry Sinych Mgieł nad miastem'],
  ['Los Angeles', 'Stany Zjednoczone', '🇺🇸', 'na', 3900, 'Hollywood, Getty Center, Venice Beach i tacos'],
  ['Las Vegas', 'Stany Zjednoczone', '🇺🇸', 'na', 650, 'Strip w neonach i Wielki Kanion na wyciągnięcie drogi'],
  ['Meksyk', 'Meksyk', '🇲🇽', 'na', 9200, 'Zócalo, Teotihuacán, muzeum antropologii i dom Fridy'],
  ['Miami', 'Stany Zjednoczone', '🇺🇸', 'na', 6100, 'Art déco South Beach, Little Havana i Everglades'],
  ['Montreal', 'Kanada', '🇨🇦', 'na', 1800, 'Stare Miasto, jazzowy festiwal i francuska Ameryka'],
  ['Merida', 'Meksyk', '🇲🇽', 'na', 920, 'Kolonialna stolica Jukatanu, cenoty i ruiny Majów wokół'],
  ['Monterrey', 'Meksyk', '🇲🇽', 'na', 1140, 'Góra Siodło, park Fundidora i wąwóz Huasteca'],
  ['Managua', 'Nikaragua', '🇳🇮', 'na', 1050, 'Jezioro z wulkanami i kolonialna Granada obok'],
  ['Nowy Jork', 'Stany Zjednoczone', '🇺🇸', 'na', 8300, 'Central Park, MoMA, Broadway i panorama z mostu'],
  ['Nowy Orlean', 'Stany Zjednoczone', '🇺🇸', 'na', 370, 'French Quarter, jazz na Frenchmen Street i Mardi Gras'],
  ['Nashville', 'Stany Zjednoczone', '🇺🇸', 'na', 690, 'Grand Ole Opry i country w każdym barze na Broadwayu'],
  ['Ottawa', 'Kanada', '🇨🇦', 'na', 1000, 'Parlament na wzgórzu i kanał Rideau jako lodowisko zimą'],
  ['Oaxaca', 'Meksyk', '🇲🇽', 'na', 270, 'Mole, mezcal, Monte Albán i Día de Muertos'],
  ['Orlando', 'Stany Zjednoczone', '🇺🇸', 'na', 310, 'Walt Disney World i Universal — stolica parków rozrywki'],
  ['Portland', 'Stany Zjednoczone', '🇺🇸', 'na', 650, 'Powell’s Books, browary rzemieślnicze i Mount Hood'],
  ['Panama', 'Panama', '🇵🇦', 'na', 900, 'Śluzy Miraflores, Casco Viejo i szlak w dżunglę'],
  ['Puebla', 'Meksyk', '🇲🇽', 'na', 1700, 'Kafle talavera, mole poblano i wulkan Popocatépetl'],
  ['Phoenix', 'Stany Zjednoczone', '🇺🇸', 'na', 1650, 'Ogród kaktusów, Sedona i pustynia Sonora'],
  ['Quebec', 'Kanada', '🇨🇦', 'na', 550, 'Jedyne mury obronne w Ameryce Płn. i Château Frontenac'],
  ['Querétaro', 'Meksyk', '🇲🇽', 'na', 1050, 'Akwedukt z 74 arkadami i kolonialne centrum z listy UNESCO'],
  ['San Francisco', 'Stany Zjednoczone', '🇺🇸', 'na', 810, 'Golden Gate, tramwaje linowe, Alcatraz i mgła'],
  ['Seattle', 'Stany Zjednoczone', '🇺🇸', 'na', 750, 'Pike Place Market, Space Needle i Mount Rainier'],
  ['San Diego', 'Stany Zjednoczone', '🇺🇸', 'na', 1380, 'Balboa Park, zoo i plaże na cały rok'],
  ['Santo Domingo', 'Dominikana', '🇩🇴', 'na', 1100, 'Najstarsze europejskie miasto Ameryk i Zona Colonial'],
  ['San José', 'Kostaryka', '🇨🇷', 'na', 350, 'Muzeum Złota i wulkany oraz chmurne lasy dookoła'],
  ['San Juan', 'Portoryko', '🇵🇷', 'na', 340, 'Forty El Morro, kolorowe Viejo San Juan i bioluminescencyjne zatoki'],
  ['San Antonio', 'Stany Zjednoczone', '🇺🇸', 'na', 1470, 'Alamo, River Walk i hiszpańskie misje'],
  ['Toronto', 'Kanada', '🇨🇦', 'na', 2900, 'CN Tower, wielokulturowe dzielnice i Niagara godzinę dalej'],
  ['Tijuana', 'Meksyk', '🇲🇽', 'na', 1900, 'Kuchnia Baja, winnice Valle de Guadalupe i granica w tle'],
  ['Tucson', 'Stany Zjednoczone', '🇺🇸', 'na', 545, 'Kaktusy saguaro, Muzeum Pustyni i obserwatoria na szczytach'],
  ['Vancouver', 'Kanada', '🇨🇦', 'na', 675, 'Stanley Park, ocean i góry narciarskie w jednym widoku'],
  ['Veracruz', 'Meksyk', '🇲🇽', 'na', 600, 'Karnawał, fort San Juan de Ulúa i muzyka son jarocho'],
  ['Waszyngton', 'Stany Zjednoczone', '🇺🇸', 'na', 680, 'National Mall i darmowe muzea Smithsonian'],
  ['Winnipeg', 'Kanada', '🇨🇦', 'na', 750, 'Muzeum Praw Człowieka i widelec rzek The Forks'],

  // -------------------------------------------------------- Ameryka Południowa
  ['Arequipa', 'Peru', '🇵🇪', 'sa', 1100, 'Białe miasto z sillaru, klasztor Santa Catalina i Kanion Colca'],
  ['Asunción', 'Paragwaj', '🇵🇾', 'sa', 520, 'Kolonialne centrum nad rzeką i misje jezuickie w kraju'],
  ['Antofagasta', 'Chile', '🇨🇱', 'sa', 390, 'Skalny łuk La Portada i najczystsze niebo świata nad Atakamą'],
  ['Buenos Aires', 'Argentyna', '🇦🇷', 'sa', 15000, 'Tango w San Telmo, Recoleta, La Boca i steki'],
  ['Bogota', 'Kolumbia', '🇨🇴', 'sa', 7900, 'Muzeum Złota, La Candelaria i Monserrate nad miastem'],
  ['Belo Horizonte', 'Brazylia', '🇧🇷', 'sa', 2500, 'Pampulha Niemeyera i barokowe miasteczka Minas Gerais'],
  ['Brasília', 'Brazylia', '🇧🇷', 'sa', 3100, 'Cała stolica zaprojektowana przez Niemeyera i Costę'],
  ['Barranquilla', 'Kolumbia', '🇨🇴', 'sa', 1300, 'Drugi największy karnawał świata i delta Magdaleny'],
  ['Bariloche', 'Argentyna', '🇦🇷', 'sa', 135, 'Alpejskie miasteczko nad jeziorem, czekolada i narty w Andach'],
  ['Cartagena', 'Kolumbia', '🇨🇴', 'sa', 1000, 'Mury obronne, kolorowe Getsemaní i Karaiby'],
  ['Cusco', 'Peru', '🇵🇪', 'sa', 430, 'Mury Inków, Święta Dolina i pociąg do Machu Picchu'],
  ['Kurytyba', 'Brazylia', '🇧🇷', 'sa', 1960, 'Ogród botaniczny, Oko Muzeum i pociąg przez Serra do Mar'],
  ['Caracas', 'Wenezuela', '🇻🇪', 'sa', 2000, 'Kolejka na Ávilę i modernizm miasta uniwersyteckiego'],
  ['Cali', 'Kolumbia', '🇨🇴', 'sa', 2200, 'Światowa stolica salsy i plantacje kawy pod bokiem'],
  ['Córdoba', 'Argentyna', '🇦🇷', 'sa', 1500, 'Jezuicki kwartał z listy UNESCO i studenckie noce'],
  ['Cuenca', 'Ekwador', '🇪🇨', 'sa', 400, 'Andyjskie kolonialne miasto i kapelusze panama u źródła'],
  ['Florianópolis', 'Brazylia', '🇧🇷', 'sa', 510, 'Wyspa z czterdziestoma plażami i laguną Conceição'],
  ['Fortaleza', 'Brazylia', '🇧🇷', 'sa', 2700, 'Plaże Ceará, wydmy Jericoacoara i forró co wieczór'],
  ['Guayaquil', 'Ekwador', '🇪🇨', 'sa', 2700, 'Malecón 2000, dzielnica Las Peñas i lot na Galapagos'],
  ['Georgetown', 'Gujana', '🇬🇾', 'sa', 120, 'Drewniana architektura kolonialna i wodospad Kaieteur'],
  ['Iquitos', 'Peru', '🇵🇪', 'sa', 480, 'Największe miasto bez drogi dojazdowej — brama w Amazonię'],
  ['Lima', 'Peru', '🇵🇪', 'sa', 9700, 'Klify Miraflores, Barranco i najlepsze restauracje kontynentu'],
  ['La Paz', 'Boliwia', '🇧🇴', 'sa', 830, 'Kolejki linowe nad kanionem i Dolina Księżycowa'],
  ['Manaus', 'Brazylia', '🇧🇷', 'sa', 2250, 'Opera w środku dżungli i spotkanie wód Amazonki'],
  ['Medellín', 'Kolumbia', '🇨🇴', 'sa', 2600, 'Metrocable nad Comuną 13, Botero i wieczna wiosna'],
  ['Montevideo', 'Urugwaj', '🇺🇾', 'sa', 1400, 'Rambla wzdłuż całego miasta, Ciudad Vieja i asado'],
  ['Mendoza', 'Argentyna', '🇦🇷', 'sa', 1100, 'Winnice malbeca pod Aconcaguą'],
  ['Natal', 'Brazylia', '🇧🇷', 'sa', 890, 'Wydmy Genipabu, bugi po piasku i najczystsze powietrze Ameryk'],
  ['Olinda', 'Brazylia', '🇧🇷', 'sa', 390, 'Barokowe wzgórza nad Recife i karnawał z gigantycznymi kukłami'],
  ['Porto Alegre', 'Brazylia', '🇧🇷', 'sa', 1490, 'Gaucho, churrasco i zachody słońca nad Guaíbą'],
  ['Potosí', 'Boliwia', '🇧🇴', 'sa', 240, 'Srebrna góra Cerro Rico, która finansowała imperium Hiszpanii'],
  ['Puerto Montt', 'Chile', '🇨🇱', 'sa', 245, 'Brama w Patagonię, fiordy i wyspa Chiloé'],
  ['Quito', 'Ekwador', '🇪🇨', 'sa', 1900, 'Najlepiej zachowana kolonialna starówka Ameryk i równik obok'],
  ['Rio de Janeiro', 'Brazylia', '🇧🇷', 'sa', 6700, 'Chrystus Zbawiciel, Copacabana, Głowa Cukru i karnawał'],
  ['Recife', 'Brazylia', '🇧🇷', 'sa', 1650, 'Kanały zwane brazylijską Wenecją i rafy przy plaży'],
  ['Rosario', 'Argentyna', '🇦🇷', 'sa', 1300, 'Pomnik Flagi nad Paraną i miasto, z którego jest Messi'],
  ['Santiago', 'Chile', '🇨🇱', 'sa', 5600, 'Andy nad miastem, Cerro San Cristóbal i winnice dookoła'],
  ['São Paulo', 'Brazylia', '🇧🇷', 'sa', 12300, 'MASP, Beco do Batman, targ miejski i kuchnia całego świata'],
  ['Salvador', 'Brazylia', '🇧🇷', 'sa', 2900, 'Pelourinho, capoeira i afrobrazylijskie serce kraju'],
  ['Sucre', 'Boliwia', '🇧🇴', 'sa', 300, 'Białe kolonialne miasto i tropy dinozaurów pod nim'],
  ['Salta', 'Argentyna', '🇦🇷', 'sa', 620, 'Kolorowe Andy, Tren a las Nubes i wąwóz Humahuaca'],
  ['Santa Marta', 'Kolumbia', '🇨🇴', 'sa', 515, 'Tayrona, Zaginione Miasto i najstarsze miasto Kolumbii'],
  ['Trujillo', 'Peru', '🇵🇪', 'sa', 920, 'Chan Chan z gliny i świątynie Moche'],
  ['Valparaíso', 'Chile', '🇨🇱', 'sa', 295, 'Kolorowe wzgórza, windy linowe i murale nad Pacyfikiem'],
  ['Valdivia', 'Chile', '🇨🇱', 'sa', 150, 'Niemieckie browary, lwy morskie na targu i rzeki'],

  // ------------------------------------------------------- Australia i Oceania
  ['Auckland', 'Nowa Zelandia', '🇳🇿', 'oc', 1700, 'Sky Tower, 48 wulkanów i żagle w zatoce'],
  ['Adelaide', 'Australia', '🇦🇺', 'oc', 1400, 'Winnice Barossa i miasto festiwali w parkowym pierścieniu'],
  ['Brisbane', 'Australia', '🇦🇺', 'oc', 2600, 'South Bank z plażą w mieście i Moreton Bay'],
  ['Canberra', 'Australia', '🇦🇺', 'oc', 460, 'Parlament pod trawnikiem i galeria narodowa'],
  ['Cairns', 'Australia', '🇦🇺', 'oc', 155, 'Wielka Rafa Koralowa i las deszczowy Daintree'],
  ['Christchurch', 'Nowa Zelandia', '🇳🇿', 'oc', 390, 'Miasto odbudowane po trzęsieniu i Alpy Południowe obok'],
  ['Darwin', 'Australia', '🇦🇺', 'oc', 150, 'Targ Mindil Beach o zachodzie i Park Kakadu'],
  ['Dunedin', 'Nowa Zelandia', '🇳🇿', 'oc', 135, 'Szkocka architektura, pingwiny i albatrosy na półwyspie Otago'],
  ['Gold Coast', 'Australia', '🇦🇺', 'oc', 700, 'Surfers Paradise, 57 km plaż i lasy Springbrook'],
  ['Hobart', 'Australia', '🇦🇺', 'oc', 255, 'Muzeum MONA, Salamanca Market i Tasmania za progiem'],
  ['Hamilton', 'Nowa Zelandia', '🇳🇿', 'oc', 185, 'Ogrody tematyczne i Hobbiton pół godziny dalej'],
  ['Melbourne', 'Australia', '🇦🇺', 'oc', 5100, 'Zaułki z kawą i street artem, sport i Great Ocean Road'],
  ['Newcastle', 'Australia', '🇦🇺', 'oc', 320, 'Baseny oceaniczne, plaże surferów i dolina Hunter'],
  ['Perth', 'Australia', '🇦🇺', 'oc', 2200, 'Kings Park, wyspa Rottnest i quokki'],
  ['Port Moresby', 'Papua-Nowa Gwinea', '🇵🇬', 'oc', 400, 'Muzeum narodowe i szlak Kokoda w górach'],
  ['Papeete', 'Polinezja Francuska', '🇵🇫', 'oc', 135, 'Targ Tahiti, czarne plaże i laguny Moorea'],
  ['Sydney', 'Australia', '🇦🇺', 'oc', 5300, 'Opera, most Harbour, Bondi i Góry Błękitne'],
  ['Tauranga', 'Nowa Zelandia', '🇳🇿', 'oc', 160, 'Mount Maunganui nad plażą i gorące źródła w okolicy'],
  ['Wellington', 'Nowa Zelandia', '🇳🇿', 'oc', 215, 'Te Papa, kolejka linowa i studio efektów Władcy Pierścieni'],
  ['Wollongong', 'Australia', '🇦🇺', 'oc', 310, 'Klifowa droga Sea Cliff Bridge i buddyjska świątynia Nan Tien'],
];

/* Dostępne też dla modułów (narzędzia w Node), nieszkodliwe w przeglądarce. */
if (typeof module !== 'undefined') module.exports = { MIASTA, KONTYNENTY };
